using UnityEngine;
using UnityEngine.Events;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Protocol;
using UnityEngine.Profiling;

namespace Poukoute {
    public partial class ConfigureManager : MonoBehaviour {
        public readonly Dictionary<string, string> ConfigurePath = new Dictionary<string, string>() {
            {typeof(MapResourceProductionConf).Name, "terrain_resource_production" },
            {typeof(MapBasicTypeConf).Name, "terrain_basic_type" },
            {typeof(ResourceBasicTypeConf).Name, "resource_basic_type" },
            {typeof(HeroArmyTypeConf).Name, "army_type" },
            {typeof(HeroAttributeConf).Name, "hero_attribute" },
            {typeof(HeroBaseConf).Name, "hero_attribute_basic" },
            {typeof(HeroLevelConf).Name, "hero_levels" },
            {typeof(GachaGroupConf).Name, "gacha_group" },
            {typeof(ResourceTroopConf).Name, "terrain_resource_troop" },
            {typeof(AudioHeroConf).Name, "hero_audio" },
            {typeof(AudioSKillConf).Name, "skill_audio" },
            {typeof(HeroBattleConf).Name, "art_animation_hero" },
            {typeof(BuildingConf).Name, "building" },
            {typeof(FteStepConf).Name, "fte_step" },
            {typeof(DramaConf).Name, "chapter_task" },
            {typeof(ChapterConf).Name, "chapter" },
            {typeof(TileEnemyConf).Name, "enemy_heroes_level_show" },
            {typeof(TileRewardConf).Name, "terrain_resource_reward" },
            {typeof(HeroRarityConf).Name, "hero_rarity" },
            {typeof(HeroSkillDefaultConf).Name, "default_hero_skill_value" },
            {typeof(SkillConf).Name, "skill" },
            {typeof(MiniMapCityConf).Name, "mini_map_city" },
            {typeof(MiniMapPassConf).Name, "mini_map_pass" },
            {typeof(PassConf).Name, "pass" },
            {typeof(FirstDownRewardConf).Name, "fd_field_reward" },
            {typeof(PointsLimitConf).Name, "points_limit" },
            {typeof(NPCCityConf).Name, "npc_city" },
            {typeof(TributeConf).Name, "tribute" },
            {typeof(TreasureConf).Name, "treasure_map_reward" },
            {typeof(ArmyCampConf).Name, "army_camp" },
            {typeof(WarehouseAttributeConf).Name, "warehouse_attribute" },
            {typeof(ResourceProduceConf).Name, "resource_produce_building" },
            {typeof(DominantUpConf).Name, "dominant_up_building" },
            {typeof(SiegeUpConf).Name, "siege_up_building" },
            {typeof(MarchSpeedUpConf).Name, "march_speed_up_building" },
            {typeof(TributeBuildingConf).Name, "tribute_gold_building" },
            {typeof(TaskConf).Name, "task" },
            {typeof(DailyTaskConf).Name, "task_daily" },
            {typeof(DailyTaskVitalityConf).Name, "task_daily_vitality" },
            {typeof(ForceRewardConf).Name, "force_reward" },
            {typeof(OccupyPointsConf).Name, "occupy_points" },
            {typeof(CapturePointsConf).Name, "capture_points" },
            {typeof(AllianceLevelConf).Name, "alliance_level" },
            {typeof(StrongholdRecruitConf).Name, "stronghold_recruit" },
            {typeof(DailyRewardConf).Name, "daily_reward_limit" },
            {typeof(DemonTroopConf).Name, "demon_troop" },
            {typeof(ProductConf).Name, "shop_product" },
            {typeof(GemProductConf).Name, "product_gem" },
            {typeof(GoldProductConf).Name, "product_gold" },
            {typeof(DailyGiftConf).Name, "daily_gift" },
            {typeof(MonthCardConf).Name, "month_card" },
            {typeof(PlayerHeroAvatarConf).Name, "player_hero_avatar" },
            {typeof(HeroAttackUpConf).Name, "hero_attack_up_building" },
            {typeof(HeroDefenceUpConf).Name, "hero_defence_up_building" },
            {typeof(DurabilityUpConf).Name, "durability_up_building" },
            {typeof(AllianceLanguageConf).Name, "alliance_language" },
            {typeof(FirstPayConf).Name, "first_time_pay" },
            {typeof(LoginRewardConf).Name,"login_reward"},
        };

        //public static readonly Dictionary<string, bool> InitDict = new Dictionary<string, bool>() {
        //    {typeof(MapResourceProductionConf).Name, MapResourceProductionConf.init },
        //    {typeof(MapBasicTypeConf).Name, MapBasicTypeConf.init },
        //    {typeof(ResourceBasicTypeConf).Name, ResourceBasicTypeConf.init },
        //    {typeof(HeroArmyTypeConf).Name, HeroArmyTypeConf.init },
        //    {typeof(HeroAttributeConf).Name, HeroAttributeConf.init },
        //    {typeof(HeroBaseConf).Name, HeroBaseConf.init },
        //    {typeof(HeroLevelConf).Name, HeroLevelConf.init },
        //    {typeof(GachaGroupConf).Name, GachaGroupConf.init },
        //    {typeof(ResourceTroopConf).Name, ResourceTroopConf.init },
        //    {typeof(AudioHeroConf).Name, AudioHeroConf.init },
        //    {typeof(AudioSKillConf).Name, AudioSKillConf.init },
        //    {typeof(HeroBattleConf).Name, HeroBattleConf.init },
        //    {typeof(BuildingConf).Name, BuildingConf.init },
        //    {typeof(FteStepConf).Name, FteStepConf.init },
        //    {typeof(DramaConf).Name, DramaConf.init },
        //    {typeof(ChapterConf).Name, ChapterConf.init },
        //    {typeof(TileEnemyConf).Name, TileEnemyConf.init },
        //    {typeof(TileRewardConf).Name, TileRewardConf.init },
        //    {typeof(HeroRarityConf).Name, HeroRarityConf.init },
        //    {typeof(HeroSkillDefaultConf).Name, HeroSkillDefaultConf.init },
        //    {typeof(SkillConf).Name, SkillConf.init },
        //    {typeof(MiniMapCityConf).Name, MiniMapCityConf.init },
        //    {typeof(MiniMapPassConf).Name, MiniMapPassConf.init },
        //    {typeof(PassConf).Name, PassConf.init },
        //    {typeof(FirstDownRewardConf).Name, FirstDownRewardConf.init },
        //    {typeof(PointsLimitConf).Name, PointsLimitConf.init },
        //    {typeof(NPCCityConf).Name, NPCCityConf.init },
        //    {typeof(TributeConf).Name, TributeConf.init },
        //    {typeof(TreasureConf).Name, TreasureConf.init },
        //    {typeof(ArmyCampConf).Name, ArmyCampConf.init },
        //    {typeof(WarehouseAttributeConf).Name, WarehouseAttributeConf.init },
        //    {typeof(ResourceProduceConf).Name, ResourceProduceConf.init },
        //    {typeof(DominantUpConf).Name, DominantUpConf.init },
        //    {typeof(SiegeUpConf).Name, SiegeUpConf.init },
        //    {typeof(MarchSpeedUpConf).Name, MarchSpeedUpConf.init },
        //    {typeof(TributeBuildingConf).Name, MapResourceProductionConf.init },
        //    {typeof(TaskConf).Name, TaskConf.init },
        //    {typeof(DailyTaskConf).Name, DailyTaskConf.init },
        //    {typeof(DailyTaskVitalityConf).Name, DailyTaskVitalityConf.init },
        //    {typeof(ForceRewardConf).Name, ForceRewardConf.init },
        //    {typeof(OccupyPointsConf).Name, OccupyPointsConf.init },
        //    {typeof(CapturePointsConf).Name, CapturePointsConf.init },
        //    {typeof(AllianceLevelConf).Name, AllianceLevelConf.init },
        //    {typeof(StrongholdRecruitConf).Name, StrongholdRecruitConf.init },
        //    {typeof(DailyRewardConf).Name, DailyRewardConf.init },
        //    {typeof(DemonTroopConf).Name, DemonTroopConf.init },
        //    {typeof(ProductConf).Name, ProductConf.init },
        //    {typeof(GemProductConf).Name, GemProductConf.init },
        //    {typeof(GoldProductConf).Name, GoldProductConf.init },
        //    {typeof(DailyGiftConf).Name, DailyGiftConf.init},
        //    {typeof(MonthCardConf).Name, MonthCardConf.init },
        //    {typeof(PlayerHeroAvatarConf).Name, PlayerHeroAvatarConf.init },
        //    {typeof(HeroAttackUpConf).Name, HeroAttackUpConf.init },
        //    {typeof(HeroDefenceUpConf).Name, HeroDefenceUpConf.init },
        //    {typeof(DurabilityUpConf).Name, DurabilityUpConf.init },
        //    {typeof(AllianceLanguageConf).Name, AllianceLanguageConf.init },
        //    {typeof(FirstPayConf).Name, FirstPayConf.init },
        //    {typeof(LoginRewardConf).Name,LoginRewardConf.init},
        //};
    }
}
