// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ack_log.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	ack_log.proto
	acknowledge.proto
	api.proto
	battle_report.proto
	cast.proto
	models.proto
	notify.proto
	request.proto
	static_map.proto
	struct.proto
	types.proto

It has these top-level messages:
	AckLog
	AddFteStepsAck
	AllianceChatAck
	ApprovalJoinAck
	BuildAck
	CallbackTroopAck
	CancelBuildAck
	CancelGiveUpBuildingAck
	CancelMarchAck
	FeedBlocksAck
	GiveupBuildingAck
	JoinAllianceAck
	KickMemberAck
	LevelUpAck
	MarchAck
	MarkBattleReportReadAck
	MarkPersonalMessagesReadAck
	MarkSystemMessageReadAck
	PayLiberationAck
	PromoteAck
	QuitAllianceAck
	DissolveAllianceAck
	ReadHeroAck
	RefuseJoinAck
	ReturnTroopImmediatelyAck
	SendAllianceMessageAck
	SetAllianceAck
	SetPlayerDescAck
	UpgradeAck
	WorldChatAck
	StateChatAck
	HeartbeatAck
	PayExtraBuildQueueAck
	SetMaxFteStepAck
	ErrorAck
	ReconnectAck
	ConnectAck
	LoginAck
	PlayerPointsAck
	AbandonPointAck
	GetHeroesAck
	EditTroopAck
	LotteryAck
	OpenChestAck
	GetBattleReportsAck
	GetBattleReportAck
	GetSystemMessagesAck
	OpenAttachmentAck
	GetPersonalMessagesAck
	GetPersonalMessageAck
	GetWorldChatAck
	GetStateChatAck
	GetTributeAck
	GetTreasureMapRewardAck
	GetTaskDailyAck
	GetTasksAck
	GetTaskRewardAck
	GetVitalityRewardAck
	GetChapterTasksAck
	GetChapterTaskRewardAck
	GetChapterRewardAck
	RankAck
	AllianceRankAck
	AllianceOccupationRankAck
	GetDominationRankAck
	GetCaptureRankAck
	GetCapturePersonalPointsAck
	GetMeleeRankAck
	GetOccupyRankAck
	GetOccupySelfRankAck
	GetMonsterPointsAck
	AddMarkAck
	DelMarkAck
	CreateAllianceAck
	GetAlliancesAck
	SearchAllianceAck
	GetAllianceAck
	GetAllianceMembersAck
	GetMyAllianceAck
	GetPlayerPublicInfoAck
	GetAllianceMessagesAck
	GetLiberationCostAck
	GetAllianceFallenTargetsAck
	GetAllianceFallenPlayersAck
	AddAllianceMarkAck
	DelAllianceMarkAck
	GetPointPlayerTroopsAck
	GetFallenInfoAck
	GetPointNpcTroopsAck
	GetHeroesInfoAck
	GetCustomerServiceTokenAck
	GetRecentCoordByLevelAck
	GetCanAddForceCoordAck
	GetRecentMonsterByLevelAck
	GetMonsterByCoordAck
	ChangeNameAck
	GetForceRewardAck
	GetForceRewardStatusAck
	SendPersonalMessageAck
	DailyChestStatusAck
	GetStoreInfoAck
	GemExchangeGoldAck
	BuyProductAck
	GetMonthCardRewardAck
	OrderConfirmAck
	OccupyLogsAck
	CaptureLogsAck
	OrderUpdateAck
	IsMonthCardExpiredAck
	DominationNotCallCityAck
	DominationInfoAck
	DominationHistoryAck
	GetDominationByCoordAck
	DominationRewardInfoAck
	GenerateBossAck
	GetMonsterRefreshAtAck
	ChangeAvatarAck
	RecruitMaxAck
	RecruitAllAck
	CancelRecruitAck
	GetBornPointsAck
	GetDailyShopAck
	ExchangeTroopHeroAck
	GetDailyLimitExpiredAck
	GetAllyCoordsAck
	GetAllAlliancePointsAck
	RechargeRewardInfoAck
	GetRechargeRewardAck
	ApiReq
	ApiAck
	TestMessage
	Battle
	ResortAllianceRanksCst
	ResortPlayerRanksCst
	ResortMonsterRanksCst
	ProduceResourcesCst
	NotifyChangesCst
	FinishAbdicationEventsCst
	FinishMarchEventsCst
	FinishRecruitEventsCst
	FinishBuildEventsCst
	FinishAbandonEventsCst
	FinishRevokeEventsCst
	FinishDissolveEventsCst
	CheckActivityCst
	PlayerCst
	GetPlayerPublicInfoCst
	GetFallenInfoCst
	GetNpcTroopsCst
	GetPlayerTroopsCst
	FeedBlocksCst
	MarchCst
	CancelMarchCst
	CallbackTroopCst
	AbandonPointCst
	RecruitMaxCst
	RecruitAllCst
	CancelRecruitCst
	EditTroopCst
	CreateAllianceCst
	GetAllianceCst
	GetAllianceMembersCst
	SearchAllianceCst
	GetAlliancesCst
	JoinAllianceCst
	RefuseJoinCst
	ApprovalJoinCst
	KickMemberCst
	PromoteCst
	SetAllianceCst
	AddAllianceMarkCst
	DelAllianceMarkCst
	GetAllianceSlavesCst
	PayLiberationCst
	BuildCst
	UpgradeCst
	CancelBuildCst
	GiveUpBuildingCst
	CancelGiveUpBuildingCst
	GetRecentCoordByLevelCst
	GetCanAddForceCoordCst
	GetRecentMonsterByLevelCst
	GetMonsterByCoordCst
	GetDominationByCoordCst
	LevelUpCst
	LotteryCst
	OpenChestCst
	GetTaskRewardCst
	GetVitalityRewardCst
	GetChapterTaskRewardCst
	GetTaskDailyCst
	GetChapterRewardCst
	AllianceChatCst
	SendAllianceMessageCst
	ReturnTroopImmediatelyCst
	GetForceRewardCst
	GetCapturePersonalPointsCst
	LoginCst
	ExchangeTroopHeroCst
	GetDailyLimitExpiredCst
	SetActivityCst
	Resources
	ResourcesCollected
	FallenTarget
	Skill
	NpcHero
	Hero
	Currency
	CurrencyCollected
	BattleReport
	PersonalMessage
	HeroFragment
	CommonReward
	SystemMessage
	FieldFirstDown
	Tribute
	Task
	Daily
	ChapterTask
	Chest
	DailyGift
	TreasureMap
	Mark
	PlayerMarks
	JoinCondition
	AllianceJoinRequest
	DailyLimit
	ForceRewards
	MonthCard
	HeroItem
	DailyShop
	FeedBlocksNtf
	FeedBlockMonsterNtf
	FeedBlockDominationNtf
	FeedBlocksMarchesNtf
	ActivityNtf
	EventMarchNtf
	EventRecruitNtf
	EventAbandonNtf
	EventGiveUpNtf
	EventBuildNtf
	HeroesNtf
	PlayerPointNtf
	FteStepNtf
	PlayerBuildingNtf
	ResourcesNtf
	ResourcesLimitNtf
	CurrencyNtf
	NewBattleReportCountNtf
	NewSystemMessageCountNtf
	NewPersonalMessageCountNtf
	NewPersonalMessageNtf
	WorldChatNtf
	StateChatNtf
	TroopArrivedNtf
	FieldFirstDownNtf
	NewTroopNtf
	TroopNtf
	ForceNtf
	NewTasksCountNtf
	ChapterTaskChangeNtf
	TaskChangeNtf
	PointLimitNtf
	TreasureMapNtf
	AllMarksNtf
	AllianceMarkNtf
	AllianceMarksNtf
	RelationNtf
	AllianceMessageNtf
	FieldFirstDownRewardNtf
	EventMarchesNtf
	ChestsNtf
	DailyLimitNtf
	ResourcesProductionNtf
	FteNtf
	AlertsNtf
	ResourcesCollectedNtf
	CurrencyCollectedNtf
	PaymentSuccessNtf
	TroopHasBeenAttackedNtf
	MiniMapAllyCoordsNtf
	MiniMapAllianceCoordsNtf
	AllianceInfosNtf
	ShortIdNtf
	RechargeRewardNtf
	HeartbeatReq
	ReconnectReq
	ConnectReq
	LoginReq
	FeedBlocksReq
	MarchReq
	AbandonPointReq
	GetHeroesReq
	ReadHeroReq
	RecruitMaxReq
	RecruitAllReq
	PlayerPointsReq
	EditTroopReq
	AddFteStepsReq
	BuildReq
	UpgradeReq
	CancelMarchReq
	CallbackTroopReq
	CancelBuildReq
	LotteryReq
	GetBattleReportsReq
	GetBattleReportReq
	NotifiesReq
	SendPersonalMessageReq
	MarkBattleReportReadReq
	GetSystemMessagesReq
	OpenAttachmentReq
	MarkSystemMessageReadReq
	GetPersonalMessagesReq
	GetPersonalMessageReq
	MarkPersonalMessagesReadReq
	GetWorldChatReq
	WorldChatReq
	GetStateChatReq
	StateChatReq
	GetTributeReq
	GetTasksReq
	GetTaskDailyReq
	GetTaskRewardReq
	GetVitalityRewardReq
	GetChapterTasksReq
	GetChapterTaskRewardReq
	GetChapterRewardReq
	LevelUpReq
	GetTreasureMapRewardReq
	CancelRecruitReq
	RankReq
	AllianceRankReq
	GetCaptureRankReq
	GetCapturePersonalPointsReq
	GetMeleeRankReq
	GetOccupyRankReq
	GetOccupySelfRankReq
	GetMonsterPointsReq
	AddMarkReq
	DelMarkReq
	CreateAllianceReq
	SetAllianceReq
	GetAlliancesReq
	SearchAllianceReq
	GetAllianceReq
	GetAllianceMembersReq
	JoinAllianceReq
	GetMyAllianceReq
	GetPlayerPublicInfoReq
	PromoteReq
	KickMemberReq
	QuitAllianceReq
	DissolveAllianceReq
	GetAllianceMessagesReq
	AllianceChatReq
	ApprovalJoinReq
	RefuseJoinReq
	SendAllianceMessageReq
	PayLiberationReq
	GetLiberationCostReq
	GetAllianceFallenTargetsReq
	GetAllianceFallenPlayersReq
	AddAllianceMarkReq
	DelAllianceMarkReq
	GetPointPlayerTroopsReq
	GetFallenInfoReq
	SetPlayerDescReq
	OpenChestReq
	GetPointNpcTroopsReq
	GetHeroesInfoReq
	GiveUpBuildingReq
	CancelGiveUpBuildingReq
	ReturnTroopImmediatelyReq
	GetCustomerServiceTokenReq
	GetRecentCoordByLevelReq
	GetCanAddForceCoordReq
	GetRecentMonsterByLevelReq
	GetMonsterByCoordReq
	GetMonsterRefreshAtReq
	ChangeNameReq
	GetForceRewardReq
	GetForceRewardStatusReq
	PayExtraBuildQueueReq
	AllianceOccupationRankReq
	SetMaxFteStepReq
	GetStoreInfoReq
	GemExchangeGoldReq
	BuyProductReq
	GetMonthCardRewardReq
	OrderConfirmReq
	OrderUpdateReq
	OccupyLogsReq
	OccupyRanksReq
	DominationNotCallCityReq
	GenerateBossReq
	GetDominationRankReq
	DominationInfoReq
	DominationHistoryReq
	GetDominationByCoordReq
	CaptureLogsReq
	IsMonthCardExpiredReq
	ChangeAvatarReq
	GetBornPointsReq
	GetDailyShopReq
	ExchangeTroopHeroReq
	GetDailyLimitExpired
	GetAllyCoordsReq
	GetAllAlliancePointsReq
	GetDailyLimitExpiredReq
	RechargeRewardInfoReq
	GetRechargeRewardReq
	StaticMap
	Player
	Point
	Block
	Monster
	Boss
	MonsterBlock
	BossBlock
	HeroPosition
	NpcTroop
	IntegralReward
	AllianceReward
	LastBloodReward
	RankReward
	Message
	Base
	Melee
	Occupy
	Capture
	DominationList
	Domination
	DominationInfo
	DominationHistory
	CapturePersonalPoints
	Activity
	BossTroop
	MonsterTroop
	Troop
	EventMarch
	EventRecruit
	EventAbdication
	EventAbandon
	EventGiveUp
	EventBuild
	EventDissolve
	LotteryResult
	ChatMessage
	ChatRoom
	RankDomination
	RankMelee
	RankCapture
	RankOccupy
	OccupySelf
	CaptureLog
	OccupyLog
	RankPlayer
	RankAlliance
	Alliance
	AllianceCache
	AllianceMember
	PlayerPublicInfo
	AllianceMessageChat
	AllianceMessageInfo
	AllianceMessageJoinRequest
	AllianceMessage
	FallenPlayer
	FallenInfo
	OrderInfo
	Formation
	AllianceBasicInfo
	Coord
	PointInfo
	ElementMonster
	ElementResource
	ElementNpcCity
	ElementCamp
	ElementPass
	ElementBuilding
	AllianceOwnedPoint
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AckLog struct {
	Uid              *string `protobuf:"bytes,1,req,name=Uid" json:"Uid,omitempty"`
	TimeStamp        *int64  `protobuf:"varint,2,req,name=TimeStamp" json:"TimeStamp,omitempty"`
	ServerId         *string `protobuf:"bytes,3,req,name=ServerId" json:"ServerId,omitempty"`
	Data             []byte  `protobuf:"bytes,4,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AckLog) Reset()                    { *m = AckLog{} }
func (m *AckLog) String() string            { return proto.CompactTextString(m) }
func (*AckLog) ProtoMessage()               {}
func (*AckLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AckLog) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *AckLog) GetTimeStamp() int64 {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return 0
}

func (m *AckLog) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *AckLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AckLog)(nil), "protocol.AckLog")
}

func init() { proto.RegisterFile("ack_log.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0xce, 0x8e,
	0xcf, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39,
	0x4a, 0x19, 0x5c, 0x6c, 0x8e, 0xc9, 0xd9, 0x3e, 0xf9, 0xe9, 0x42, 0x02, 0x5c, 0xcc, 0xa1, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x0c, 0x17, 0x67, 0x48, 0x66,
	0x6e, 0x6a, 0x70, 0x49, 0x62, 0x6e, 0x81, 0x04, 0x93, 0x02, 0x93, 0x06, 0x73, 0x10, 0x42, 0x40,
	0x48, 0x8a, 0x8b, 0x23, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0xc8, 0x33, 0x45, 0x82, 0x19, 0xac, 0x09,
	0xce, 0x17, 0x12, 0xe2, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x51, 0x60, 0xd2, 0xe0, 0x09,
	0x02, 0xb3, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xd3, 0xc7, 0xe6, 0x83, 0x00, 0x00, 0x00,
}
