// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle_report.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Battle struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Battle) Reset()                    { *m = Battle{} }
func (m *Battle) String() string            { return proto.CompactTextString(m) }
func (*Battle) ProtoMessage()               {}
func (*Battle) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type Battle_Deaths struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Amount           *int32  `protobuf:"varint,2,req,name=Amount" json:"Amount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Battle_Deaths) Reset()                    { *m = Battle_Deaths{} }
func (m *Battle_Deaths) String() string            { return proto.CompactTextString(m) }
func (*Battle_Deaths) ProtoMessage()               {}
func (*Battle_Deaths) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

func (m *Battle_Deaths) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Battle_Deaths) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type Battle_BasicInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	AllianceName     *string `protobuf:"bytes,2,req,name=AllianceName" json:"AllianceName,omitempty"`
	AllianceEmblem   *int32  `protobuf:"varint,3,req,name=AllianceEmblem" json:"AllianceEmblem,omitempty"`
	Id               *string `protobuf:"bytes,4,req,name=Id" json:"Id,omitempty"`
	Avatar           *int32  `protobuf:"varint,5,req,name=Avatar" json:"Avatar,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Battle_BasicInfo) Reset()                    { *m = Battle_BasicInfo{} }
func (m *Battle_BasicInfo) String() string            { return proto.CompactTextString(m) }
func (*Battle_BasicInfo) ProtoMessage()               {}
func (*Battle_BasicInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 1} }

func (m *Battle_BasicInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Battle_BasicInfo) GetAllianceName() string {
	if m != nil && m.AllianceName != nil {
		return *m.AllianceName
	}
	return ""
}

func (m *Battle_BasicInfo) GetAllianceEmblem() int32 {
	if m != nil && m.AllianceEmblem != nil {
		return *m.AllianceEmblem
	}
	return 0
}

func (m *Battle_BasicInfo) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Battle_BasicInfo) GetAvatar() int32 {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return 0
}

type Battle_PlayerInfo struct {
	BasicInfo        *Battle_BasicInfo `protobuf:"bytes,1,req,name=BasicInfo" json:"BasicInfo,omitempty"`
	TotalPower       *int32            `protobuf:"varint,2,req,name=TotalPower" json:"TotalPower,omitempty"`
	RemainPower      *int32            `protobuf:"varint,3,req,name=RemainPower" json:"RemainPower,omitempty"`
	Rating           *int32            `protobuf:"varint,4,req,name=Rating" json:"Rating,omitempty"`
	BeforeHeroes     []*Battle_Hero    `protobuf:"bytes,10,rep,name=BeforeHeroes" json:"BeforeHeroes,omitempty"`
	AfterHeroes      []*Battle_Hero    `protobuf:"bytes,11,rep,name=AfterHeroes" json:"AfterHeroes,omitempty"`
	Deaths           []*Battle_Deaths  `protobuf:"bytes,12,rep,name=Deaths" json:"Deaths,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Battle_PlayerInfo) Reset()                    { *m = Battle_PlayerInfo{} }
func (m *Battle_PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*Battle_PlayerInfo) ProtoMessage()               {}
func (*Battle_PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 2} }

func (m *Battle_PlayerInfo) GetBasicInfo() *Battle_BasicInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *Battle_PlayerInfo) GetTotalPower() int32 {
	if m != nil && m.TotalPower != nil {
		return *m.TotalPower
	}
	return 0
}

func (m *Battle_PlayerInfo) GetRemainPower() int32 {
	if m != nil && m.RemainPower != nil {
		return *m.RemainPower
	}
	return 0
}

func (m *Battle_PlayerInfo) GetRating() int32 {
	if m != nil && m.Rating != nil {
		return *m.Rating
	}
	return 0
}

func (m *Battle_PlayerInfo) GetBeforeHeroes() []*Battle_Hero {
	if m != nil {
		return m.BeforeHeroes
	}
	return nil
}

func (m *Battle_PlayerInfo) GetAfterHeroes() []*Battle_Hero {
	if m != nil {
		return m.AfterHeroes
	}
	return nil
}

func (m *Battle_PlayerInfo) GetDeaths() []*Battle_Deaths {
	if m != nil {
		return m.Deaths
	}
	return nil
}

type Battle_Result struct {
	FinalInfo        *Battle_Result_Final  `protobuf:"bytes,1,req,name=FinalInfo" json:"FinalInfo,omitempty"`
	PvpInfo          *Battle_Result_Common `protobuf:"bytes,2,opt,name=PvpInfo" json:"PvpInfo,omitempty"`
	PveInfo          *Battle_Result_Pve    `protobuf:"bytes,3,opt,name=PveInfo" json:"PveInfo,omitempty"`
	SiegeInfo        *Battle_Result_Siege  `protobuf:"bytes,4,opt,name=SiegeInfo" json:"SiegeInfo,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Battle_Result) Reset()                    { *m = Battle_Result{} }
func (m *Battle_Result) String() string            { return proto.CompactTextString(m) }
func (*Battle_Result) ProtoMessage()               {}
func (*Battle_Result) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3} }

func (m *Battle_Result) GetFinalInfo() *Battle_Result_Final {
	if m != nil {
		return m.FinalInfo
	}
	return nil
}

func (m *Battle_Result) GetPvpInfo() *Battle_Result_Common {
	if m != nil {
		return m.PvpInfo
	}
	return nil
}

func (m *Battle_Result) GetPveInfo() *Battle_Result_Pve {
	if m != nil {
		return m.PveInfo
	}
	return nil
}

func (m *Battle_Result) GetSiegeInfo() *Battle_Result_Siege {
	if m != nil {
		return m.SiegeInfo
	}
	return nil
}

type Battle_Result_Common struct {
	RemainTroops     *int32 `protobuf:"varint,1,req,name=RemainTroops" json:"RemainTroops,omitempty"`
	NextTroopType    *int32 `protobuf:"varint,2,req,name=NextTroopType" json:"NextTroopType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Battle_Result_Common) Reset()                    { *m = Battle_Result_Common{} }
func (m *Battle_Result_Common) String() string            { return proto.CompactTextString(m) }
func (*Battle_Result_Common) ProtoMessage()               {}
func (*Battle_Result_Common) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3, 0} }

func (m *Battle_Result_Common) GetRemainTroops() int32 {
	if m != nil && m.RemainTroops != nil {
		return *m.RemainTroops
	}
	return 0
}

func (m *Battle_Result_Common) GetNextTroopType() int32 {
	if m != nil && m.NextTroopType != nil {
		return *m.NextTroopType
	}
	return 0
}

type Battle_Result_Pve struct {
	RemainTroops     *int32 `protobuf:"varint,1,req,name=RemainTroops" json:"RemainTroops,omitempty"`
	CurrentNumber    *int32 `protobuf:"varint,2,req,name=CurrentNumber" json:"CurrentNumber,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Battle_Result_Pve) Reset()                    { *m = Battle_Result_Pve{} }
func (m *Battle_Result_Pve) String() string            { return proto.CompactTextString(m) }
func (*Battle_Result_Pve) ProtoMessage()               {}
func (*Battle_Result_Pve) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3, 1} }

func (m *Battle_Result_Pve) GetRemainTroops() int32 {
	if m != nil && m.RemainTroops != nil {
		return *m.RemainTroops
	}
	return 0
}

func (m *Battle_Result_Pve) GetCurrentNumber() int32 {
	if m != nil && m.CurrentNumber != nil {
		return *m.CurrentNumber
	}
	return 0
}

type Battle_Result_Siege struct {
	DurabilityLose   *int32 `protobuf:"varint,1,req,name=DurabilityLose" json:"DurabilityLose,omitempty"`
	DurabilityRemain *int32 `protobuf:"varint,2,req,name=DurabilityRemain" json:"DurabilityRemain,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Battle_Result_Siege) Reset()                    { *m = Battle_Result_Siege{} }
func (m *Battle_Result_Siege) String() string            { return proto.CompactTextString(m) }
func (*Battle_Result_Siege) ProtoMessage()               {}
func (*Battle_Result_Siege) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3, 2} }

func (m *Battle_Result_Siege) GetDurabilityLose() int32 {
	if m != nil && m.DurabilityLose != nil {
		return *m.DurabilityLose
	}
	return 0
}

func (m *Battle_Result_Siege) GetDurabilityRemain() int32 {
	if m != nil && m.DurabilityRemain != nil {
		return *m.DurabilityRemain
	}
	return 0
}

type Battle_Result_Final struct {
	Fallen           *bool  `protobuf:"varint,1,req,name=Fallen" json:"Fallen,omitempty"`
	Broken           *bool  `protobuf:"varint,2,req,name=Broken" json:"Broken,omitempty"`
	Occupy           *bool  `protobuf:"varint,3,req,name=Occupy" json:"Occupy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Battle_Result_Final) Reset()                    { *m = Battle_Result_Final{} }
func (m *Battle_Result_Final) String() string            { return proto.CompactTextString(m) }
func (*Battle_Result_Final) ProtoMessage()               {}
func (*Battle_Result_Final) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3, 3} }

func (m *Battle_Result_Final) GetFallen() bool {
	if m != nil && m.Fallen != nil {
		return *m.Fallen
	}
	return false
}

func (m *Battle_Result_Final) GetBroken() bool {
	if m != nil && m.Broken != nil {
		return *m.Broken
	}
	return false
}

func (m *Battle_Result_Final) GetOccupy() bool {
	if m != nil && m.Occupy != nil {
		return *m.Occupy
	}
	return false
}

type Battle_Report struct {
	Attacker         *Battle_PlayerInfo `protobuf:"bytes,1,req,name=Attacker" json:"Attacker,omitempty"`
	Defender         *Battle_PlayerInfo `protobuf:"bytes,2,req,name=Defender" json:"Defender,omitempty"`
	Winner           *string            `protobuf:"bytes,3,req,name=Winner" json:"Winner,omitempty"`
	Result           *Battle_Result     `protobuf:"bytes,4,req,name=Result" json:"Result,omitempty"`
	PointInfo        *PointInfo         `protobuf:"bytes,5,req,name=PointInfo" json:"PointInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Battle_Report) Reset()                    { *m = Battle_Report{} }
func (m *Battle_Report) String() string            { return proto.CompactTextString(m) }
func (*Battle_Report) ProtoMessage()               {}
func (*Battle_Report) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 4} }

func (m *Battle_Report) GetAttacker() *Battle_PlayerInfo {
	if m != nil {
		return m.Attacker
	}
	return nil
}

func (m *Battle_Report) GetDefender() *Battle_PlayerInfo {
	if m != nil {
		return m.Defender
	}
	return nil
}

func (m *Battle_Report) GetWinner() string {
	if m != nil && m.Winner != nil {
		return *m.Winner
	}
	return ""
}

func (m *Battle_Report) GetResult() *Battle_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Battle_Report) GetPointInfo() *PointInfo {
	if m != nil {
		return m.PointInfo
	}
	return nil
}

type Battle_ReportRounds struct {
	Rounds           []*Battle_Round `protobuf:"bytes,1,rep,name=Rounds" json:"Rounds,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Battle_ReportRounds) Reset()                    { *m = Battle_ReportRounds{} }
func (m *Battle_ReportRounds) String() string            { return proto.CompactTextString(m) }
func (*Battle_ReportRounds) ProtoMessage()               {}
func (*Battle_ReportRounds) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 5} }

func (m *Battle_ReportRounds) GetRounds() []*Battle_Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type Battle_Forces struct {
	AttackerHeroes   []*Battle_Hero `protobuf:"bytes,1,rep,name=AttackerHeroes" json:"AttackerHeroes,omitempty"`
	DefenderHeroes   []*Battle_Hero `protobuf:"bytes,2,rep,name=DefenderHeroes" json:"DefenderHeroes,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Battle_Forces) Reset()                    { *m = Battle_Forces{} }
func (m *Battle_Forces) String() string            { return proto.CompactTextString(m) }
func (*Battle_Forces) ProtoMessage()               {}
func (*Battle_Forces) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 6} }

func (m *Battle_Forces) GetAttackerHeroes() []*Battle_Hero {
	if m != nil {
		return m.AttackerHeroes
	}
	return nil
}

func (m *Battle_Forces) GetDefenderHeroes() []*Battle_Hero {
	if m != nil {
		return m.DefenderHeroes
	}
	return nil
}

type Battle_Hero struct {
	Id                  *string  `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	Name                *string  `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Level               *int32   `protobuf:"varint,4,req,name=Level" json:"Level,omitempty"`
	ArmyAmount          *int32   `protobuf:"varint,5,req,name=ArmyAmount" json:"ArmyAmount,omitempty"`
	ArmyAmountBonus     *float32 `protobuf:"fixed32,6,req,name=ArmyAmountBonus" json:"ArmyAmountBonus,omitempty"`
	Force               *string  `protobuf:"bytes,7,req,name=Force" json:"Force,omitempty"`
	Speed               *int32   `protobuf:"varint,10,req,name=Speed" json:"Speed,omitempty"`
	Attack              *int32   `protobuf:"varint,11,req,name=Attack" json:"Attack,omitempty"`
	Defence             *int32   `protobuf:"varint,12,req,name=Defence" json:"Defence,omitempty"`
	Position            *int32   `protobuf:"varint,13,req,name=Position" json:"Position,omitempty"`
	DeadAmount          *int32   `protobuf:"varint,14,req,name=DeadAmount" json:"DeadAmount,omitempty"`
	TotalDamage         *int32   `protobuf:"varint,15,req,name=TotalDamage" json:"TotalDamage,omitempty"`
	TotalHeal           *int32   `protobuf:"varint,16,req,name=TotalHeal" json:"TotalHeal,omitempty"`
	SkillTriggeredTimes *int32   `protobuf:"varint,20,req,name=SkillTriggeredTimes" json:"SkillTriggeredTimes,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *Battle_Hero) Reset()                    { *m = Battle_Hero{} }
func (m *Battle_Hero) String() string            { return proto.CompactTextString(m) }
func (*Battle_Hero) ProtoMessage()               {}
func (*Battle_Hero) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 7} }

func (m *Battle_Hero) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Battle_Hero) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Battle_Hero) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Battle_Hero) GetArmyAmount() int32 {
	if m != nil && m.ArmyAmount != nil {
		return *m.ArmyAmount
	}
	return 0
}

func (m *Battle_Hero) GetArmyAmountBonus() float32 {
	if m != nil && m.ArmyAmountBonus != nil {
		return *m.ArmyAmountBonus
	}
	return 0
}

func (m *Battle_Hero) GetForce() string {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return ""
}

func (m *Battle_Hero) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Battle_Hero) GetAttack() int32 {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return 0
}

func (m *Battle_Hero) GetDefence() int32 {
	if m != nil && m.Defence != nil {
		return *m.Defence
	}
	return 0
}

func (m *Battle_Hero) GetPosition() int32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *Battle_Hero) GetDeadAmount() int32 {
	if m != nil && m.DeadAmount != nil {
		return *m.DeadAmount
	}
	return 0
}

func (m *Battle_Hero) GetTotalDamage() int32 {
	if m != nil && m.TotalDamage != nil {
		return *m.TotalDamage
	}
	return 0
}

func (m *Battle_Hero) GetTotalHeal() int32 {
	if m != nil && m.TotalHeal != nil {
		return *m.TotalHeal
	}
	return 0
}

func (m *Battle_Hero) GetSkillTriggeredTimes() int32 {
	if m != nil && m.SkillTriggeredTimes != nil {
		return *m.SkillTriggeredTimes
	}
	return 0
}

type Battle_Round struct {
	Actions          []*Battle_Action `protobuf:"bytes,1,rep,name=Actions" json:"Actions,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Battle_Round) Reset()                    { *m = Battle_Round{} }
func (m *Battle_Round) String() string            { return proto.CompactTextString(m) }
func (*Battle_Round) ProtoMessage()               {}
func (*Battle_Round) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 8} }

func (m *Battle_Round) GetActions() []*Battle_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type Battle_Action struct {
	HeroId           *string          `protobuf:"bytes,1,req,name=HeroId" json:"HeroId,omitempty"`
	Type             *string          `protobuf:"bytes,2,req,name=Type" json:"Type,omitempty"`
	Name             *string          `protobuf:"bytes,3,req,name=Name" json:"Name,omitempty"`
	Amount           *int32           `protobuf:"varint,4,req,name=Amount" json:"Amount,omitempty"`
	Speed            *int32           `protobuf:"varint,5,req,name=Speed" json:"Speed,omitempty"`
	Rounds           *int32           `protobuf:"varint,6,req,name=Rounds" json:"Rounds,omitempty"`
	RemainAmount     *int32           `protobuf:"varint,7,req,name=RemainAmount" json:"RemainAmount,omitempty"`
	DispelName       *string          `protobuf:"bytes,8,req,name=DispelName" json:"DispelName,omitempty"`
	Percent          *float32         `protobuf:"fixed32,9,req,name=Percent" json:"Percent,omitempty"`
	IsHalo           *bool            `protobuf:"varint,10,req,name=IsHalo" json:"IsHalo,omitempty"`
	Trigger          *string          `protobuf:"bytes,11,req,name=Trigger" json:"Trigger,omitempty"`
	ToSelf           *bool            `protobuf:"varint,12,req,name=ToSelf" json:"ToSelf,omitempty"`
	Via              *string          `protobuf:"bytes,13,req,name=Via" json:"Via,omitempty"`
	Positions        []int32          `protobuf:"varint,14,rep,name=Positions" json:"Positions,omitempty"`
	Actions          []*Battle_Action `protobuf:"bytes,20,rep,name=Actions" json:"Actions,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Battle_Action) Reset()                    { *m = Battle_Action{} }
func (m *Battle_Action) String() string            { return proto.CompactTextString(m) }
func (*Battle_Action) ProtoMessage()               {}
func (*Battle_Action) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 9} }

func (m *Battle_Action) GetHeroId() string {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return ""
}

func (m *Battle_Action) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Battle_Action) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Battle_Action) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Battle_Action) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Battle_Action) GetRounds() int32 {
	if m != nil && m.Rounds != nil {
		return *m.Rounds
	}
	return 0
}

func (m *Battle_Action) GetRemainAmount() int32 {
	if m != nil && m.RemainAmount != nil {
		return *m.RemainAmount
	}
	return 0
}

func (m *Battle_Action) GetDispelName() string {
	if m != nil && m.DispelName != nil {
		return *m.DispelName
	}
	return ""
}

func (m *Battle_Action) GetPercent() float32 {
	if m != nil && m.Percent != nil {
		return *m.Percent
	}
	return 0
}

func (m *Battle_Action) GetIsHalo() bool {
	if m != nil && m.IsHalo != nil {
		return *m.IsHalo
	}
	return false
}

func (m *Battle_Action) GetTrigger() string {
	if m != nil && m.Trigger != nil {
		return *m.Trigger
	}
	return ""
}

func (m *Battle_Action) GetToSelf() bool {
	if m != nil && m.ToSelf != nil {
		return *m.ToSelf
	}
	return false
}

func (m *Battle_Action) GetVia() string {
	if m != nil && m.Via != nil {
		return *m.Via
	}
	return ""
}

func (m *Battle_Action) GetPositions() []int32 {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *Battle_Action) GetActions() []*Battle_Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Battle)(nil), "protocol.Battle")
	proto.RegisterType((*Battle_Deaths)(nil), "protocol.Battle.Deaths")
	proto.RegisterType((*Battle_BasicInfo)(nil), "protocol.Battle.BasicInfo")
	proto.RegisterType((*Battle_PlayerInfo)(nil), "protocol.Battle.PlayerInfo")
	proto.RegisterType((*Battle_Result)(nil), "protocol.Battle.Result")
	proto.RegisterType((*Battle_Result_Common)(nil), "protocol.Battle.Result.Common")
	proto.RegisterType((*Battle_Result_Pve)(nil), "protocol.Battle.Result.Pve")
	proto.RegisterType((*Battle_Result_Siege)(nil), "protocol.Battle.Result.Siege")
	proto.RegisterType((*Battle_Result_Final)(nil), "protocol.Battle.Result.Final")
	proto.RegisterType((*Battle_Report)(nil), "protocol.Battle.Report")
	proto.RegisterType((*Battle_ReportRounds)(nil), "protocol.Battle.ReportRounds")
	proto.RegisterType((*Battle_Forces)(nil), "protocol.Battle.Forces")
	proto.RegisterType((*Battle_Hero)(nil), "protocol.Battle.Hero")
	proto.RegisterType((*Battle_Round)(nil), "protocol.Battle.Round")
	proto.RegisterType((*Battle_Action)(nil), "protocol.Battle.Action")
}

func init() { proto.RegisterFile("battle_report.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 1015 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x5d, 0x6f, 0x23, 0x35,
	0x17, 0x56, 0x26, 0x1f, 0xcd, 0x9c, 0x74, 0xbb, 0x95, 0xdb, 0x77, 0x5f, 0x6b, 0x80, 0x55, 0xb4,
	0x42, 0x28, 0xe2, 0x22, 0xb0, 0x15, 0x68, 0x17, 0x10, 0x48, 0xe9, 0x96, 0xaa, 0x95, 0x56, 0x6d,
	0xe4, 0x46, 0x70, 0xc1, 0x05, 0x72, 0x27, 0xa7, 0x65, 0xd4, 0x99, 0x71, 0xe4, 0x71, 0x0a, 0xf9,
	0x03, 0xfc, 0x01, 0x24, 0x04, 0x3f, 0x08, 0x7e, 0x12, 0xd7, 0xc8, 0xc7, 0x9e, 0x8f, 0x34, 0x6d,
	0xd9, 0xab, 0xcc, 0x73, 0xce, 0xf3, 0xd8, 0xc7, 0x3e, 0x1f, 0x0e, 0xec, 0x5d, 0x4a, 0x63, 0x52,
	0xfc, 0x51, 0xe3, 0x42, 0x69, 0x33, 0x5e, 0x68, 0x65, 0x14, 0xeb, 0xd3, 0x4f, 0xac, 0xd2, 0x68,
	0x60, 0x56, 0x0b, 0x2c, 0x9c, 0xf9, 0xc5, 0x1f, 0x7b, 0xd0, 0x3b, 0x24, 0x7a, 0xf4, 0x19, 0xf4,
	0x8e, 0x50, 0x9a, 0x9f, 0x0a, 0xc6, 0xa0, 0x73, 0x26, 0x33, 0xe4, 0xad, 0x61, 0x30, 0x0a, 0x05,
	0x7d, 0xb3, 0x67, 0xd0, 0x9b, 0x64, 0x6a, 0x99, 0x1b, 0x1e, 0x0c, 0x83, 0x51, 0x57, 0x78, 0x14,
	0xfd, 0xd6, 0x82, 0xf0, 0x50, 0x16, 0x49, 0x7c, 0x9a, 0x5f, 0xa9, 0x7b, 0x95, 0x2f, 0x60, 0x7b,
	0x92, 0xa6, 0x89, 0xcc, 0x63, 0x24, 0x5f, 0x40, 0xbe, 0x35, 0x1b, 0xfb, 0x08, 0x76, 0x4a, 0xfc,
	0x6d, 0x76, 0x99, 0x62, 0xc6, 0xdb, 0xb4, 0xcb, 0x1d, 0x2b, 0xdb, 0x81, 0xe0, 0x74, 0xce, 0x3b,
	0xb4, 0x42, 0x70, 0x3a, 0xa7, 0xa8, 0x6e, 0xa5, 0x91, 0x9a, 0x77, 0x7d, 0x54, 0x84, 0xa2, 0xbf,
	0x02, 0x80, 0x69, 0x2a, 0x57, 0xa8, 0x29, 0xac, 0xd7, 0x8d, 0x18, 0x29, 0xb6, 0xc1, 0x41, 0x34,
	0x2e, 0x2f, 0x64, 0xec, 0xce, 0x3f, 0xae, 0x18, 0xa2, 0x71, 0xa0, 0xe7, 0x00, 0x33, 0x65, 0x64,
	0x3a, 0x55, 0x3f, 0xa3, 0xf6, 0x47, 0x6f, 0x58, 0xd8, 0x10, 0x06, 0x02, 0x33, 0x99, 0xe4, 0x8e,
	0xe0, 0xa2, 0x6e, 0x9a, 0x6c, 0x88, 0x42, 0x9a, 0x24, 0xbf, 0xa6, 0xb0, 0xbb, 0xc2, 0x23, 0xf6,
	0x05, 0x6c, 0x1f, 0xe2, 0x95, 0xd2, 0x78, 0x82, 0x5a, 0x61, 0xc1, 0x61, 0xd8, 0x1e, 0x0d, 0x0e,
	0xfe, 0xb7, 0x11, 0x96, 0x75, 0x8b, 0x35, 0x2a, 0x7b, 0x05, 0x83, 0xc9, 0x95, 0x41, 0xed, 0x95,
	0x83, 0xc7, 0x94, 0x4d, 0x26, 0xfb, 0xa4, 0x4c, 0x31, 0xdf, 0x26, 0xcd, 0xff, 0x37, 0x34, 0xce,
	0x2d, 0x3c, 0x2d, 0xfa, 0xbb, 0x03, 0x3d, 0x81, 0xc5, 0x32, 0x35, 0xec, 0x2b, 0x08, 0x8f, 0x93,
	0x5c, 0xa6, 0x8d, 0x3b, 0xfc, 0x60, 0x43, 0xee, 0xb8, 0x63, 0x22, 0x8a, 0x9a, 0xcf, 0x5e, 0xc3,
	0xd6, 0xf4, 0x76, 0x41, 0xd2, 0x60, 0xd8, 0x1a, 0x0d, 0x0e, 0x9e, 0x3f, 0x24, 0x7d, 0xa3, 0xb2,
	0x4c, 0xe5, 0xa2, 0xa4, 0xb3, 0xcf, 0xad, 0x12, 0x49, 0xd9, 0x26, 0xe5, 0x7b, 0x0f, 0x29, 0xa7,
	0xb7, 0x28, 0x4a, 0xae, 0x8d, 0xf6, 0x22, 0xc1, 0x6b, 0x27, 0xec, 0x90, 0xf0, 0xc1, 0x68, 0x89,
	0x28, 0x6a, 0x7e, 0x24, 0xa0, 0xe7, 0xc2, 0xb0, 0xb5, 0xeb, 0x72, 0x39, 0xd3, 0x4a, 0x2d, 0x0a,
	0x3a, 0x77, 0x57, 0xac, 0xd9, 0xd8, 0x87, 0xf0, 0xe4, 0x0c, 0x7f, 0x31, 0x84, 0x66, 0xab, 0x05,
	0xfa, 0x2a, 0x59, 0x37, 0x46, 0xe7, 0xd0, 0x9e, 0xde, 0xe2, 0xbb, 0x2e, 0xf8, 0x66, 0xa9, 0x35,
	0xe6, 0xe6, 0x6c, 0x99, 0x5d, 0x56, 0x65, 0xb7, 0x6e, 0x8c, 0x7e, 0x80, 0x2e, 0x45, 0x6c, 0x7b,
	0xe7, 0x68, 0xa9, 0xe5, 0x65, 0x92, 0x26, 0x66, 0xf5, 0x56, 0x15, 0xe8, 0x17, 0xbd, 0x63, 0x65,
	0x1f, 0xc3, 0x6e, 0x6d, 0x71, 0x1b, 0xfa, 0x95, 0x37, 0xec, 0xd1, 0x39, 0x74, 0x29, 0x79, 0xb6,
	0x7a, 0x8f, 0x65, 0x9a, 0x62, 0x4e, 0x8b, 0xf6, 0x85, 0x47, 0xd6, 0x7e, 0xa8, 0xd5, 0x0d, 0xba,
	0x25, 0xfa, 0xc2, 0x23, 0x6b, 0x3f, 0x8f, 0xe3, 0xe5, 0x62, 0x45, 0xad, 0xd0, 0x17, 0x1e, 0x45,
	0xff, 0xb4, 0x6c, 0x21, 0xd9, 0x79, 0xc4, 0x5e, 0x41, 0x7f, 0x62, 0x8c, 0x8c, 0x6f, 0x50, 0xfb,
	0x3a, 0xda, 0x4c, 0x69, 0xdd, 0xbb, 0xa2, 0x22, 0x5b, 0xe1, 0x11, 0x5e, 0x61, 0x3e, 0xf7, 0x57,
	0xf2, 0x5f, 0xc2, 0x92, 0x6c, 0x83, 0xfa, 0x3e, 0xc9, 0x73, 0xdf, 0x9f, 0xa1, 0xf0, 0xc8, 0xb6,
	0x83, 0x2b, 0x01, 0x6a, 0xcd, 0xfb, 0xda, 0xc1, 0xb9, 0x45, 0xd9, 0x03, 0x2f, 0x21, 0x9c, 0xaa,
	0x24, 0x37, 0x54, 0x55, 0x5d, 0xd2, 0xec, 0xd5, 0x9a, 0xca, 0x25, 0x6a, 0x56, 0xf4, 0x8d, 0x4d,
	0xb8, 0x3d, 0xb7, 0x50, 0xcb, 0x7c, 0x5e, 0xb0, 0x31, 0xf4, 0xdc, 0x17, 0x6f, 0x51, 0x0b, 0x3e,
	0xdb, 0xdc, 0xd3, 0xba, 0x85, 0x67, 0x45, 0xbf, 0xb6, 0xa0, 0x77, 0xac, 0x74, 0x8c, 0x05, 0xfb,
	0x1a, 0x76, 0xca, 0xbb, 0xf0, 0x9d, 0xdf, 0x7a, 0xac, 0xf3, 0xef, 0x90, 0xad, 0xbc, 0xbc, 0x11,
	0x2f, 0x0f, 0x1e, 0x95, 0xaf, 0x93, 0xa3, 0xdf, 0xdb, 0xd0, 0xb1, 0x9f, 0x7e, 0x06, 0xb7, 0xaa,
	0x19, 0x5c, 0xce, 0xfc, 0xa0, 0x31, 0xf3, 0xf7, 0xa1, 0xfb, 0x16, 0x6f, 0x31, 0xf5, 0x33, 0xcf,
	0x01, 0x3b, 0x4c, 0x27, 0x3a, 0x5b, 0xf9, 0x77, 0xc4, 0x4d, 0xec, 0x86, 0x85, 0x8d, 0xe0, 0x69,
	0x8d, 0x0e, 0x55, 0xbe, 0x2c, 0x78, 0x6f, 0x18, 0x8c, 0x02, 0x71, 0xd7, 0x6c, 0xd7, 0xa7, 0x4b,
	0xe1, 0x5b, 0xb4, 0xa9, 0x03, 0xd6, 0x7a, 0xb1, 0x40, 0x9c, 0x73, 0x70, 0xbb, 0x12, 0xa0, 0x37,
	0x82, 0x6e, 0x82, 0x0f, 0xfc, 0x1b, 0x41, 0x88, 0x71, 0xd8, 0xa2, 0x23, 0xc6, 0xc8, 0xb7, 0xc9,
	0x51, 0x42, 0x16, 0x41, 0x7f, 0xaa, 0x8a, 0xc4, 0x24, 0x2a, 0xe7, 0x4f, 0xc8, 0x55, 0x61, 0x7b,
	0x86, 0x23, 0x94, 0x73, 0x7f, 0x86, 0x1d, 0x77, 0x86, 0xda, 0x62, 0x1f, 0x04, 0x7a, 0x1e, 0x8e,
	0x64, 0x26, 0xaf, 0x91, 0x3f, 0x75, 0x0f, 0x42, 0xc3, 0xc4, 0xde, 0x87, 0x90, 0xe0, 0x09, 0xca,
	0x94, 0xef, 0x92, 0xbf, 0x36, 0xb0, 0x4f, 0x61, 0xef, 0xe2, 0x26, 0x49, 0xd3, 0x99, 0x4e, 0xae,
	0xaf, 0x51, 0xe3, 0x7c, 0x96, 0x64, 0x58, 0xf0, 0x7d, 0xe2, 0xdd, 0xe7, 0x8a, 0xbe, 0x84, 0x2e,
	0xd5, 0x0a, 0x7b, 0x09, 0x5b, 0x93, 0xd8, 0x06, 0x59, 0x16, 0xc6, 0x66, 0x3d, 0x3b, 0xbf, 0x28,
	0x79, 0xd1, 0x9f, 0x6d, 0xe8, 0xb9, 0x6f, 0x7b, 0x4d, 0x36, 0xbd, 0x55, 0x6a, 0x3d, 0xb2, 0xe9,
	0xad, 0xa6, 0x5a, 0x28, 0xe8, 0xbb, 0x4a, 0x79, 0xfb, 0xde, 0x3f, 0x08, 0x9d, 0xe6, 0x1f, 0x84,
	0x3a, 0x29, 0xdd, 0x3b, 0x49, 0xf1, 0x6d, 0xd0, 0xf3, 0xaf, 0xa2, 0x6b, 0x8f, 0x6a, 0x3e, 0xfa,
	0xb5, 0xb6, 0x9a, 0xf3, 0xd1, 0xaf, 0x68, 0x53, 0x90, 0x14, 0x0b, 0x4c, 0x29, 0x86, 0x3e, 0xc5,
	0xd0, 0xb0, 0xd8, 0xc4, 0x4e, 0x51, 0xc7, 0x98, 0x1b, 0x1e, 0x52, 0xf9, 0x94, 0xd0, 0xee, 0x7a,
	0x5a, 0x9c, 0xc8, 0x54, 0x51, 0x85, 0xf4, 0x85, 0x47, 0x56, 0xe1, 0x2f, 0x95, 0x6a, 0x24, 0x14,
	0x25, 0xb4, 0x8a, 0x99, 0xba, 0xc0, 0xf4, 0x8a, 0x6a, 0xa4, 0x2f, 0x3c, 0x62, 0xbb, 0xd0, 0xfe,
	0x2e, 0x91, 0x54, 0x1d, 0xa1, 0xb0, 0x9f, 0x36, 0xad, 0x65, 0x91, 0x14, 0x7c, 0x67, 0xd8, 0xb6,
	0x69, 0xad, 0x0c, 0xcd, 0xdc, 0xec, 0xbf, 0x5b, 0x6e, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0x9c, 0x54, 0xf3, 0xc7, 0x09, 0x00, 0x00,
}
