// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cast.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResortAllianceRanksCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResortAllianceRanksCst) Reset()                    { *m = ResortAllianceRanksCst{} }
func (m *ResortAllianceRanksCst) String() string            { return proto.CompactTextString(m) }
func (*ResortAllianceRanksCst) ProtoMessage()               {}
func (*ResortAllianceRanksCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type ResortPlayerRanksCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResortPlayerRanksCst) Reset()                    { *m = ResortPlayerRanksCst{} }
func (m *ResortPlayerRanksCst) String() string            { return proto.CompactTextString(m) }
func (*ResortPlayerRanksCst) ProtoMessage()               {}
func (*ResortPlayerRanksCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

type ResortMonsterRanksCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ResortMonsterRanksCst) Reset()                    { *m = ResortMonsterRanksCst{} }
func (m *ResortMonsterRanksCst) String() string            { return proto.CompactTextString(m) }
func (*ResortMonsterRanksCst) ProtoMessage()               {}
func (*ResortMonsterRanksCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type ProduceResourcesCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ProduceResourcesCst) Reset()                    { *m = ProduceResourcesCst{} }
func (m *ProduceResourcesCst) String() string            { return proto.CompactTextString(m) }
func (*ProduceResourcesCst) ProtoMessage()               {}
func (*ProduceResourcesCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

type NotifyChangesCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NotifyChangesCst) Reset()                    { *m = NotifyChangesCst{} }
func (m *NotifyChangesCst) String() string            { return proto.CompactTextString(m) }
func (*NotifyChangesCst) ProtoMessage()               {}
func (*NotifyChangesCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

type FinishAbdicationEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishAbdicationEventsCst) Reset()                    { *m = FinishAbdicationEventsCst{} }
func (m *FinishAbdicationEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishAbdicationEventsCst) ProtoMessage()               {}
func (*FinishAbdicationEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

type FinishMarchEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishMarchEventsCst) Reset()                    { *m = FinishMarchEventsCst{} }
func (m *FinishMarchEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishMarchEventsCst) ProtoMessage()               {}
func (*FinishMarchEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

type FinishRecruitEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishRecruitEventsCst) Reset()                    { *m = FinishRecruitEventsCst{} }
func (m *FinishRecruitEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishRecruitEventsCst) ProtoMessage()               {}
func (*FinishRecruitEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

type FinishBuildEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishBuildEventsCst) Reset()                    { *m = FinishBuildEventsCst{} }
func (m *FinishBuildEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishBuildEventsCst) ProtoMessage()               {}
func (*FinishBuildEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

type FinishAbandonEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishAbandonEventsCst) Reset()                    { *m = FinishAbandonEventsCst{} }
func (m *FinishAbandonEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishAbandonEventsCst) ProtoMessage()               {}
func (*FinishAbandonEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

type FinishRevokeEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishRevokeEventsCst) Reset()                    { *m = FinishRevokeEventsCst{} }
func (m *FinishRevokeEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishRevokeEventsCst) ProtoMessage()               {}
func (*FinishRevokeEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

type FinishDissolveEventsCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinishDissolveEventsCst) Reset()                    { *m = FinishDissolveEventsCst{} }
func (m *FinishDissolveEventsCst) String() string            { return proto.CompactTextString(m) }
func (*FinishDissolveEventsCst) ProtoMessage()               {}
func (*FinishDissolveEventsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

type CheckActivityCst struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CheckActivityCst) Reset()                    { *m = CheckActivityCst{} }
func (m *CheckActivityCst) String() string            { return proto.CompactTextString(m) }
func (*CheckActivityCst) ProtoMessage()               {}
func (*CheckActivityCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

type PlayerCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerCst) Reset()                    { *m = PlayerCst{} }
func (m *PlayerCst) String() string            { return proto.CompactTextString(m) }
func (*PlayerCst) ProtoMessage()               {}
func (*PlayerCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *PlayerCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type GetPlayerPublicInfoCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TargetId         *string `protobuf:"bytes,2,req,name=TargetId" json:"TargetId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPlayerPublicInfoCst) Reset()                    { *m = GetPlayerPublicInfoCst{} }
func (m *GetPlayerPublicInfoCst) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerPublicInfoCst) ProtoMessage()               {}
func (*GetPlayerPublicInfoCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *GetPlayerPublicInfoCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetPlayerPublicInfoCst) GetTargetId() string {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return ""
}

type GetFallenInfoCst struct {
	Pid              *string  `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coords           []*Coord `protobuf:"bytes,2,rep,name=Coords" json:"Coords,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetFallenInfoCst) Reset()                    { *m = GetFallenInfoCst{} }
func (m *GetFallenInfoCst) String() string            { return proto.CompactTextString(m) }
func (*GetFallenInfoCst) ProtoMessage()               {}
func (*GetFallenInfoCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *GetFallenInfoCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetFallenInfoCst) GetCoords() []*Coord {
	if m != nil {
		return m.Coords
	}
	return nil
}

type GetNpcTroopsCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetNpcTroopsCst) Reset()                    { *m = GetNpcTroopsCst{} }
func (m *GetNpcTroopsCst) String() string            { return proto.CompactTextString(m) }
func (*GetNpcTroopsCst) ProtoMessage()               {}
func (*GetNpcTroopsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *GetNpcTroopsCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetNpcTroopsCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type GetPlayerTroopsCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	Page             *int32  `protobuf:"varint,3,req,name=Page" json:"Page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetPlayerTroopsCst) Reset()                    { *m = GetPlayerTroopsCst{} }
func (m *GetPlayerTroopsCst) String() string            { return proto.CompactTextString(m) }
func (*GetPlayerTroopsCst) ProtoMessage()               {}
func (*GetPlayerTroopsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *GetPlayerTroopsCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetPlayerTroopsCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *GetPlayerTroopsCst) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

type FeedBlocksCst struct {
	Pid              *string  `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Offsets          []string `protobuf:"bytes,2,rep,name=Offsets" json:"Offsets,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FeedBlocksCst) Reset()                    { *m = FeedBlocksCst{} }
func (m *FeedBlocksCst) String() string            { return proto.CompactTextString(m) }
func (*FeedBlocksCst) ProtoMessage()               {}
func (*FeedBlocksCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *FeedBlocksCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *FeedBlocksCst) GetOffsets() []string {
	if m != nil {
		return m.Offsets
	}
	return nil
}

type MarchCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TroopId          *string `protobuf:"bytes,2,req,name=TroopId" json:"TroopId,omitempty"`
	MarchType        *int32  `protobuf:"varint,3,req,name=MarchType" json:"MarchType,omitempty"`
	Target           *Coord  `protobuf:"bytes,4,req,name=Target" json:"Target,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MarchCst) Reset()                    { *m = MarchCst{} }
func (m *MarchCst) String() string            { return proto.CompactTextString(m) }
func (*MarchCst) ProtoMessage()               {}
func (*MarchCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{19} }

func (m *MarchCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *MarchCst) GetTroopId() string {
	if m != nil && m.TroopId != nil {
		return *m.TroopId
	}
	return ""
}

func (m *MarchCst) GetMarchType() int32 {
	if m != nil && m.MarchType != nil {
		return *m.MarchType
	}
	return 0
}

func (m *MarchCst) GetTarget() *Coord {
	if m != nil {
		return m.Target
	}
	return nil
}

type CancelMarchCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelMarchCst) Reset()                    { *m = CancelMarchCst{} }
func (m *CancelMarchCst) String() string            { return proto.CompactTextString(m) }
func (*CancelMarchCst) ProtoMessage()               {}
func (*CancelMarchCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{20} }

func (m *CancelMarchCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CancelMarchCst) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type CallbackTroopCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CallbackTroopCst) Reset()                    { *m = CallbackTroopCst{} }
func (m *CallbackTroopCst) String() string            { return proto.CompactTextString(m) }
func (*CallbackTroopCst) ProtoMessage()               {}
func (*CallbackTroopCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{21} }

func (m *CallbackTroopCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CallbackTroopCst) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type AbandonPointCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AbandonPointCst) Reset()                    { *m = AbandonPointCst{} }
func (m *AbandonPointCst) String() string            { return proto.CompactTextString(m) }
func (*AbandonPointCst) ProtoMessage()               {}
func (*AbandonPointCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{22} }

func (m *AbandonPointCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *AbandonPointCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type RecruitMaxCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TroopId          *string `protobuf:"bytes,2,req,name=TroopId" json:"TroopId,omitempty"`
	HeroName         *string `protobuf:"bytes,3,req,name=HeroName" json:"HeroName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecruitMaxCst) Reset()                    { *m = RecruitMaxCst{} }
func (m *RecruitMaxCst) String() string            { return proto.CompactTextString(m) }
func (*RecruitMaxCst) ProtoMessage()               {}
func (*RecruitMaxCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{23} }

func (m *RecruitMaxCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *RecruitMaxCst) GetTroopId() string {
	if m != nil && m.TroopId != nil {
		return *m.TroopId
	}
	return ""
}

func (m *RecruitMaxCst) GetHeroName() string {
	if m != nil && m.HeroName != nil {
		return *m.HeroName
	}
	return ""
}

type RecruitAllCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TroopId          *string `protobuf:"bytes,2,req,name=TroopId" json:"TroopId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RecruitAllCst) Reset()                    { *m = RecruitAllCst{} }
func (m *RecruitAllCst) String() string            { return proto.CompactTextString(m) }
func (*RecruitAllCst) ProtoMessage()               {}
func (*RecruitAllCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{24} }

func (m *RecruitAllCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *RecruitAllCst) GetTroopId() string {
	if m != nil && m.TroopId != nil {
		return *m.TroopId
	}
	return ""
}

type CancelRecruitCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	EventId          *string `protobuf:"bytes,2,req,name=EventId" json:"EventId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelRecruitCst) Reset()                    { *m = CancelRecruitCst{} }
func (m *CancelRecruitCst) String() string            { return proto.CompactTextString(m) }
func (*CancelRecruitCst) ProtoMessage()               {}
func (*CancelRecruitCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{25} }

func (m *CancelRecruitCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CancelRecruitCst) GetEventId() string {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return ""
}

type EditTroopCst struct {
	Pid              *string         `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TroopId          *string         `protobuf:"bytes,2,req,name=TroopId" json:"TroopId,omitempty"`
	HeroPositions    []*HeroPosition `protobuf:"bytes,3,rep,name=HeroPositions" json:"HeroPositions,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *EditTroopCst) Reset()                    { *m = EditTroopCst{} }
func (m *EditTroopCst) String() string            { return proto.CompactTextString(m) }
func (*EditTroopCst) ProtoMessage()               {}
func (*EditTroopCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{26} }

func (m *EditTroopCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *EditTroopCst) GetTroopId() string {
	if m != nil && m.TroopId != nil {
		return *m.TroopId
	}
	return ""
}

func (m *EditTroopCst) GetHeroPositions() []*HeroPosition {
	if m != nil {
		return m.HeroPositions
	}
	return nil
}

type CreateAllianceCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Desc             *string `protobuf:"bytes,3,req,name=Desc" json:"Desc,omitempty"`
	Emblem           *int32  `protobuf:"varint,4,req,name=Emblem" json:"Emblem,omitempty"`
	JoinType         *int32  `protobuf:"varint,10,req,name=JoinType" json:"JoinType,omitempty"`
	ForceLimit       *int32  `protobuf:"varint,11,req,name=ForceLimit" json:"ForceLimit,omitempty"`
	Language         *int32  `protobuf:"varint,12,req,name=Language" json:"Language,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAllianceCst) Reset()                    { *m = CreateAllianceCst{} }
func (m *CreateAllianceCst) String() string            { return proto.CompactTextString(m) }
func (*CreateAllianceCst) ProtoMessage()               {}
func (*CreateAllianceCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{27} }

func (m *CreateAllianceCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CreateAllianceCst) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateAllianceCst) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *CreateAllianceCst) GetEmblem() int32 {
	if m != nil && m.Emblem != nil {
		return *m.Emblem
	}
	return 0
}

func (m *CreateAllianceCst) GetJoinType() int32 {
	if m != nil && m.JoinType != nil {
		return *m.JoinType
	}
	return 0
}

func (m *CreateAllianceCst) GetForceLimit() int32 {
	if m != nil && m.ForceLimit != nil {
		return *m.ForceLimit
	}
	return 0
}

func (m *CreateAllianceCst) GetLanguage() int32 {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return 0
}

type GetAllianceCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	AllianceId       *string `protobuf:"bytes,2,req,name=AllianceId" json:"AllianceId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAllianceCst) Reset()                    { *m = GetAllianceCst{} }
func (m *GetAllianceCst) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceCst) ProtoMessage()               {}
func (*GetAllianceCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{28} }

func (m *GetAllianceCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetAllianceCst) GetAllianceId() string {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return ""
}

type GetAllianceMembersCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	AllianceId       *string `protobuf:"bytes,2,req,name=AllianceId" json:"AllianceId,omitempty"`
	Page             *int32  `protobuf:"varint,3,req,name=Page" json:"Page,omitempty"`
	OrderBy          *string `protobuf:"bytes,4,req,name=OrderBy" json:"OrderBy,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAllianceMembersCst) Reset()                    { *m = GetAllianceMembersCst{} }
func (m *GetAllianceMembersCst) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceMembersCst) ProtoMessage()               {}
func (*GetAllianceMembersCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{29} }

func (m *GetAllianceMembersCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetAllianceMembersCst) GetAllianceId() string {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return ""
}

func (m *GetAllianceMembersCst) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

func (m *GetAllianceMembersCst) GetOrderBy() string {
	if m != nil && m.OrderBy != nil {
		return *m.OrderBy
	}
	return ""
}

type SearchAllianceCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SearchAllianceCst) Reset()                    { *m = SearchAllianceCst{} }
func (m *SearchAllianceCst) String() string            { return proto.CompactTextString(m) }
func (*SearchAllianceCst) ProtoMessage()               {}
func (*SearchAllianceCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{30} }

func (m *SearchAllianceCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *SearchAllianceCst) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetAlliancesCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Page             *int32  `protobuf:"varint,2,req,name=Page" json:"Page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAlliancesCst) Reset()                    { *m = GetAlliancesCst{} }
func (m *GetAlliancesCst) String() string            { return proto.CompactTextString(m) }
func (*GetAlliancesCst) ProtoMessage()               {}
func (*GetAlliancesCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{31} }

func (m *GetAlliancesCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetAlliancesCst) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

type JoinAllianceCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	AllianceId       *string `protobuf:"bytes,2,req,name=AllianceId" json:"AllianceId,omitempty"`
	Message          *string `protobuf:"bytes,3,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinAllianceCst) Reset()                    { *m = JoinAllianceCst{} }
func (m *JoinAllianceCst) String() string            { return proto.CompactTextString(m) }
func (*JoinAllianceCst) ProtoMessage()               {}
func (*JoinAllianceCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{32} }

func (m *JoinAllianceCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *JoinAllianceCst) GetAllianceId() string {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return ""
}

func (m *JoinAllianceCst) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type RefuseJoinCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	RequesterId      *string `protobuf:"bytes,2,req,name=RequesterId" json:"RequesterId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RefuseJoinCst) Reset()                    { *m = RefuseJoinCst{} }
func (m *RefuseJoinCst) String() string            { return proto.CompactTextString(m) }
func (*RefuseJoinCst) ProtoMessage()               {}
func (*RefuseJoinCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{33} }

func (m *RefuseJoinCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *RefuseJoinCst) GetRequesterId() string {
	if m != nil && m.RequesterId != nil {
		return *m.RequesterId
	}
	return ""
}

type ApprovalJoinCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	RequesterId      *string `protobuf:"bytes,2,req,name=RequesterId" json:"RequesterId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ApprovalJoinCst) Reset()                    { *m = ApprovalJoinCst{} }
func (m *ApprovalJoinCst) String() string            { return proto.CompactTextString(m) }
func (*ApprovalJoinCst) ProtoMessage()               {}
func (*ApprovalJoinCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{34} }

func (m *ApprovalJoinCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *ApprovalJoinCst) GetRequesterId() string {
	if m != nil && m.RequesterId != nil {
		return *m.RequesterId
	}
	return ""
}

type KickMemberCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	MemberId         *string `protobuf:"bytes,2,req,name=MemberId" json:"MemberId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KickMemberCst) Reset()                    { *m = KickMemberCst{} }
func (m *KickMemberCst) String() string            { return proto.CompactTextString(m) }
func (*KickMemberCst) ProtoMessage()               {}
func (*KickMemberCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{35} }

func (m *KickMemberCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *KickMemberCst) GetMemberId() string {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return ""
}

type PromoteCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	MemberId         *string `protobuf:"bytes,2,req,name=MemberId" json:"MemberId,omitempty"`
	Role             *int32  `protobuf:"varint,3,req,name=Role" json:"Role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PromoteCst) Reset()                    { *m = PromoteCst{} }
func (m *PromoteCst) String() string            { return proto.CompactTextString(m) }
func (*PromoteCst) ProtoMessage()               {}
func (*PromoteCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{36} }

func (m *PromoteCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *PromoteCst) GetMemberId() string {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return ""
}

func (m *PromoteCst) GetRole() int32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type SetAllianceCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Desc             *string `protobuf:"bytes,2,req,name=Desc" json:"Desc,omitempty"`
	Emblem           *int32  `protobuf:"varint,3,req,name=Emblem" json:"Emblem,omitempty"`
	JoinType         *int32  `protobuf:"varint,10,req,name=JoinType" json:"JoinType,omitempty"`
	ForceLimit       *int32  `protobuf:"varint,11,req,name=ForceLimit" json:"ForceLimit,omitempty"`
	Language         *int32  `protobuf:"varint,12,req,name=Language" json:"Language,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetAllianceCst) Reset()                    { *m = SetAllianceCst{} }
func (m *SetAllianceCst) String() string            { return proto.CompactTextString(m) }
func (*SetAllianceCst) ProtoMessage()               {}
func (*SetAllianceCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{37} }

func (m *SetAllianceCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *SetAllianceCst) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *SetAllianceCst) GetEmblem() int32 {
	if m != nil && m.Emblem != nil {
		return *m.Emblem
	}
	return 0
}

func (m *SetAllianceCst) GetJoinType() int32 {
	if m != nil && m.JoinType != nil {
		return *m.JoinType
	}
	return 0
}

func (m *SetAllianceCst) GetForceLimit() int32 {
	if m != nil && m.ForceLimit != nil {
		return *m.ForceLimit
	}
	return 0
}

func (m *SetAllianceCst) GetLanguage() int32 {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return 0
}

type AddAllianceMarkCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	Name             *string `protobuf:"bytes,3,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AddAllianceMarkCst) Reset()                    { *m = AddAllianceMarkCst{} }
func (m *AddAllianceMarkCst) String() string            { return proto.CompactTextString(m) }
func (*AddAllianceMarkCst) ProtoMessage()               {}
func (*AddAllianceMarkCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{38} }

func (m *AddAllianceMarkCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *AddAllianceMarkCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *AddAllianceMarkCst) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DelAllianceMarkCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DelAllianceMarkCst) Reset()                    { *m = DelAllianceMarkCst{} }
func (m *DelAllianceMarkCst) String() string            { return proto.CompactTextString(m) }
func (*DelAllianceMarkCst) ProtoMessage()               {}
func (*DelAllianceMarkCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{39} }

func (m *DelAllianceMarkCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *DelAllianceMarkCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type GetAllianceSlavesCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Page             *int32  `protobuf:"varint,2,req,name=Page" json:"Page,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetAllianceSlavesCst) Reset()                    { *m = GetAllianceSlavesCst{} }
func (m *GetAllianceSlavesCst) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceSlavesCst) ProtoMessage()               {}
func (*GetAllianceSlavesCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{40} }

func (m *GetAllianceSlavesCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetAllianceSlavesCst) GetPage() int32 {
	if m != nil && m.Page != nil {
		return *m.Page
	}
	return 0
}

type PayLiberationCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Food             *int32  `protobuf:"varint,2,req,name=Food" json:"Food,omitempty"`
	Lumber           *int32  `protobuf:"varint,3,req,name=Lumber" json:"Lumber,omitempty"`
	Marble           *int32  `protobuf:"varint,4,req,name=Marble" json:"Marble,omitempty"`
	Steel            *int32  `protobuf:"varint,5,req,name=Steel" json:"Steel,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PayLiberationCst) Reset()                    { *m = PayLiberationCst{} }
func (m *PayLiberationCst) String() string            { return proto.CompactTextString(m) }
func (*PayLiberationCst) ProtoMessage()               {}
func (*PayLiberationCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{41} }

func (m *PayLiberationCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *PayLiberationCst) GetFood() int32 {
	if m != nil && m.Food != nil {
		return *m.Food
	}
	return 0
}

func (m *PayLiberationCst) GetLumber() int32 {
	if m != nil && m.Lumber != nil {
		return *m.Lumber
	}
	return 0
}

func (m *PayLiberationCst) GetMarble() int32 {
	if m != nil && m.Marble != nil {
		return *m.Marble
	}
	return 0
}

func (m *PayLiberationCst) GetSteel() int32 {
	if m != nil && m.Steel != nil {
		return *m.Steel
	}
	return 0
}

type BuildCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Coord            *Coord  `protobuf:"bytes,3,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuildCst) Reset()                    { *m = BuildCst{} }
func (m *BuildCst) String() string            { return proto.CompactTextString(m) }
func (*BuildCst) ProtoMessage()               {}
func (*BuildCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{42} }

func (m *BuildCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *BuildCst) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BuildCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type UpgradeCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpgradeCst) Reset()                    { *m = UpgradeCst{} }
func (m *UpgradeCst) String() string            { return proto.CompactTextString(m) }
func (*UpgradeCst) ProtoMessage()               {}
func (*UpgradeCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{43} }

func (m *UpgradeCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *UpgradeCst) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type CancelBuildCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	EventId          *string `protobuf:"bytes,2,req,name=EventId" json:"EventId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelBuildCst) Reset()                    { *m = CancelBuildCst{} }
func (m *CancelBuildCst) String() string            { return proto.CompactTextString(m) }
func (*CancelBuildCst) ProtoMessage()               {}
func (*CancelBuildCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{44} }

func (m *CancelBuildCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CancelBuildCst) GetEventId() string {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return ""
}

type GiveUpBuildingCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	BuildingName     *string `protobuf:"bytes,2,req,name=BuildingName" json:"BuildingName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GiveUpBuildingCst) Reset()                    { *m = GiveUpBuildingCst{} }
func (m *GiveUpBuildingCst) String() string            { return proto.CompactTextString(m) }
func (*GiveUpBuildingCst) ProtoMessage()               {}
func (*GiveUpBuildingCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{45} }

func (m *GiveUpBuildingCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GiveUpBuildingCst) GetBuildingName() string {
	if m != nil && m.BuildingName != nil {
		return *m.BuildingName
	}
	return ""
}

type CancelGiveUpBuildingCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	EventId          *string `protobuf:"bytes,2,req,name=EventId" json:"EventId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelGiveUpBuildingCst) Reset()                    { *m = CancelGiveUpBuildingCst{} }
func (m *CancelGiveUpBuildingCst) String() string            { return proto.CompactTextString(m) }
func (*CancelGiveUpBuildingCst) ProtoMessage()               {}
func (*CancelGiveUpBuildingCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{46} }

func (m *CancelGiveUpBuildingCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *CancelGiveUpBuildingCst) GetEventId() string {
	if m != nil && m.EventId != nil {
		return *m.EventId
	}
	return ""
}

type GetRecentCoordByLevelCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=Level" json:"Level,omitempty"`
	Type             *int32  `protobuf:"varint,3,req,name=Type" json:"Type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRecentCoordByLevelCst) Reset()                    { *m = GetRecentCoordByLevelCst{} }
func (m *GetRecentCoordByLevelCst) String() string            { return proto.CompactTextString(m) }
func (*GetRecentCoordByLevelCst) ProtoMessage()               {}
func (*GetRecentCoordByLevelCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{47} }

func (m *GetRecentCoordByLevelCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetRecentCoordByLevelCst) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *GetRecentCoordByLevelCst) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type GetCanAddForceCoordCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetCanAddForceCoordCst) Reset()                    { *m = GetCanAddForceCoordCst{} }
func (m *GetCanAddForceCoordCst) String() string            { return proto.CompactTextString(m) }
func (*GetCanAddForceCoordCst) ProtoMessage()               {}
func (*GetCanAddForceCoordCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{48} }

func (m *GetCanAddForceCoordCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type GetRecentMonsterByLevelCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetRecentMonsterByLevelCst) Reset()                    { *m = GetRecentMonsterByLevelCst{} }
func (m *GetRecentMonsterByLevelCst) String() string            { return proto.CompactTextString(m) }
func (*GetRecentMonsterByLevelCst) ProtoMessage()               {}
func (*GetRecentMonsterByLevelCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{49} }

func (m *GetRecentMonsterByLevelCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetRecentMonsterByLevelCst) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type GetMonsterByCoordCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetMonsterByCoordCst) Reset()                    { *m = GetMonsterByCoordCst{} }
func (m *GetMonsterByCoordCst) String() string            { return proto.CompactTextString(m) }
func (*GetMonsterByCoordCst) ProtoMessage()               {}
func (*GetMonsterByCoordCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{50} }

func (m *GetMonsterByCoordCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetMonsterByCoordCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type GetDominationByCoordCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Coord            *Coord  `protobuf:"bytes,2,req,name=Coord" json:"Coord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDominationByCoordCst) Reset()                    { *m = GetDominationByCoordCst{} }
func (m *GetDominationByCoordCst) String() string            { return proto.CompactTextString(m) }
func (*GetDominationByCoordCst) ProtoMessage()               {}
func (*GetDominationByCoordCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{51} }

func (m *GetDominationByCoordCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetDominationByCoordCst) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type LevelUpCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	HeroName         *string `protobuf:"bytes,2,req,name=HeroName" json:"HeroName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LevelUpCst) Reset()                    { *m = LevelUpCst{} }
func (m *LevelUpCst) String() string            { return proto.CompactTextString(m) }
func (*LevelUpCst) ProtoMessage()               {}
func (*LevelUpCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{52} }

func (m *LevelUpCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *LevelUpCst) GetHeroName() string {
	if m != nil && m.HeroName != nil {
		return *m.HeroName
	}
	return ""
}

type LotteryCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	GroupName        *string `protobuf:"bytes,2,req,name=GroupName" json:"GroupName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LotteryCst) Reset()                    { *m = LotteryCst{} }
func (m *LotteryCst) String() string            { return proto.CompactTextString(m) }
func (*LotteryCst) ProtoMessage()               {}
func (*LotteryCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{53} }

func (m *LotteryCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *LotteryCst) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

type OpenChestCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	ChestName        *string `protobuf:"bytes,2,req,name=ChestName" json:"ChestName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OpenChestCst) Reset()                    { *m = OpenChestCst{} }
func (m *OpenChestCst) String() string            { return proto.CompactTextString(m) }
func (*OpenChestCst) ProtoMessage()               {}
func (*OpenChestCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{54} }

func (m *OpenChestCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *OpenChestCst) GetChestName() string {
	if m != nil && m.ChestName != nil {
		return *m.ChestName
	}
	return ""
}

type GetTaskRewardCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TaskId           *int32  `protobuf:"varint,2,req,name=TaskId" json:"TaskId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTaskRewardCst) Reset()                    { *m = GetTaskRewardCst{} }
func (m *GetTaskRewardCst) String() string            { return proto.CompactTextString(m) }
func (*GetTaskRewardCst) ProtoMessage()               {}
func (*GetTaskRewardCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{55} }

func (m *GetTaskRewardCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetTaskRewardCst) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

type GetVitalityRewardCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	RewardId         *int32  `protobuf:"varint,2,req,name=RewardId" json:"RewardId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetVitalityRewardCst) Reset()                    { *m = GetVitalityRewardCst{} }
func (m *GetVitalityRewardCst) String() string            { return proto.CompactTextString(m) }
func (*GetVitalityRewardCst) ProtoMessage()               {}
func (*GetVitalityRewardCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{56} }

func (m *GetVitalityRewardCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetVitalityRewardCst) GetRewardId() int32 {
	if m != nil && m.RewardId != nil {
		return *m.RewardId
	}
	return 0
}

type GetChapterTaskRewardCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TaskId           *int32  `protobuf:"varint,2,req,name=TaskId" json:"TaskId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetChapterTaskRewardCst) Reset()                    { *m = GetChapterTaskRewardCst{} }
func (m *GetChapterTaskRewardCst) String() string            { return proto.CompactTextString(m) }
func (*GetChapterTaskRewardCst) ProtoMessage()               {}
func (*GetChapterTaskRewardCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{57} }

func (m *GetChapterTaskRewardCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetChapterTaskRewardCst) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

type GetTaskDailyCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTaskDailyCst) Reset()                    { *m = GetTaskDailyCst{} }
func (m *GetTaskDailyCst) String() string            { return proto.CompactTextString(m) }
func (*GetTaskDailyCst) ProtoMessage()               {}
func (*GetTaskDailyCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{58} }

func (m *GetTaskDailyCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type GetChapterRewardCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetChapterRewardCst) Reset()                    { *m = GetChapterRewardCst{} }
func (m *GetChapterRewardCst) String() string            { return proto.CompactTextString(m) }
func (*GetChapterRewardCst) ProtoMessage()               {}
func (*GetChapterRewardCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{59} }

func (m *GetChapterRewardCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type AllianceChatCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllianceChatCst) Reset()                    { *m = AllianceChatCst{} }
func (m *AllianceChatCst) String() string            { return proto.CompactTextString(m) }
func (*AllianceChatCst) ProtoMessage()               {}
func (*AllianceChatCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{60} }

func (m *AllianceChatCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *AllianceChatCst) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type SendAllianceMessageCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Content          *string `protobuf:"bytes,2,req,name=Content" json:"Content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendAllianceMessageCst) Reset()                    { *m = SendAllianceMessageCst{} }
func (m *SendAllianceMessageCst) String() string            { return proto.CompactTextString(m) }
func (*SendAllianceMessageCst) ProtoMessage()               {}
func (*SendAllianceMessageCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{61} }

func (m *SendAllianceMessageCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *SendAllianceMessageCst) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ReturnTroopImmediatelyCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	TroopId          *string `protobuf:"bytes,2,req,name=TroopId" json:"TroopId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReturnTroopImmediatelyCst) Reset()                    { *m = ReturnTroopImmediatelyCst{} }
func (m *ReturnTroopImmediatelyCst) String() string            { return proto.CompactTextString(m) }
func (*ReturnTroopImmediatelyCst) ProtoMessage()               {}
func (*ReturnTroopImmediatelyCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{62} }

func (m *ReturnTroopImmediatelyCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *ReturnTroopImmediatelyCst) GetTroopId() string {
	if m != nil && m.TroopId != nil {
		return *m.TroopId
	}
	return ""
}

type GetForceRewardCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetForceRewardCst) Reset()                    { *m = GetForceRewardCst{} }
func (m *GetForceRewardCst) String() string            { return proto.CompactTextString(m) }
func (*GetForceRewardCst) ProtoMessage()               {}
func (*GetForceRewardCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{63} }

func (m *GetForceRewardCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *GetForceRewardCst) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type GetCapturePersonalPointsCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetCapturePersonalPointsCst) Reset()                    { *m = GetCapturePersonalPointsCst{} }
func (m *GetCapturePersonalPointsCst) String() string            { return proto.CompactTextString(m) }
func (*GetCapturePersonalPointsCst) ProtoMessage()               {}
func (*GetCapturePersonalPointsCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{64} }

func (m *GetCapturePersonalPointsCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type LoginCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	MapSN            *int32  `protobuf:"varint,2,opt,name=MapSN" json:"MapSN,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginCst) Reset()                    { *m = LoginCst{} }
func (m *LoginCst) String() string            { return proto.CompactTextString(m) }
func (*LoginCst) ProtoMessage()               {}
func (*LoginCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{65} }

func (m *LoginCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *LoginCst) GetMapSN() int32 {
	if m != nil && m.MapSN != nil {
		return *m.MapSN
	}
	return 0
}

type ExchangeTroopHeroCst struct {
	Pid              *string      `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	Formations       []*Formation `protobuf:"bytes,2,rep,name=Formations" json:"Formations,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ExchangeTroopHeroCst) Reset()                    { *m = ExchangeTroopHeroCst{} }
func (m *ExchangeTroopHeroCst) String() string            { return proto.CompactTextString(m) }
func (*ExchangeTroopHeroCst) ProtoMessage()               {}
func (*ExchangeTroopHeroCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{66} }

func (m *ExchangeTroopHeroCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *ExchangeTroopHeroCst) GetFormations() []*Formation {
	if m != nil {
		return m.Formations
	}
	return nil
}

type GetDailyLimitExpiredCst struct {
	Pid              *string `protobuf:"bytes,1,req,name=Pid" json:"Pid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDailyLimitExpiredCst) Reset()                    { *m = GetDailyLimitExpiredCst{} }
func (m *GetDailyLimitExpiredCst) String() string            { return proto.CompactTextString(m) }
func (*GetDailyLimitExpiredCst) ProtoMessage()               {}
func (*GetDailyLimitExpiredCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{67} }

func (m *GetDailyLimitExpiredCst) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

type SetActivityCst struct {
	Activity         *string `protobuf:"bytes,1,req,name=Activity" json:"Activity,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetActivityCst) Reset()                    { *m = SetActivityCst{} }
func (m *SetActivityCst) String() string            { return proto.CompactTextString(m) }
func (*SetActivityCst) ProtoMessage()               {}
func (*SetActivityCst) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{68} }

func (m *SetActivityCst) GetActivity() string {
	if m != nil && m.Activity != nil {
		return *m.Activity
	}
	return ""
}

func init() {
	proto.RegisterType((*ResortAllianceRanksCst)(nil), "protocol.ResortAllianceRanksCst")
	proto.RegisterType((*ResortPlayerRanksCst)(nil), "protocol.ResortPlayerRanksCst")
	proto.RegisterType((*ResortMonsterRanksCst)(nil), "protocol.ResortMonsterRanksCst")
	proto.RegisterType((*ProduceResourcesCst)(nil), "protocol.ProduceResourcesCst")
	proto.RegisterType((*NotifyChangesCst)(nil), "protocol.NotifyChangesCst")
	proto.RegisterType((*FinishAbdicationEventsCst)(nil), "protocol.FinishAbdicationEventsCst")
	proto.RegisterType((*FinishMarchEventsCst)(nil), "protocol.FinishMarchEventsCst")
	proto.RegisterType((*FinishRecruitEventsCst)(nil), "protocol.FinishRecruitEventsCst")
	proto.RegisterType((*FinishBuildEventsCst)(nil), "protocol.FinishBuildEventsCst")
	proto.RegisterType((*FinishAbandonEventsCst)(nil), "protocol.FinishAbandonEventsCst")
	proto.RegisterType((*FinishRevokeEventsCst)(nil), "protocol.FinishRevokeEventsCst")
	proto.RegisterType((*FinishDissolveEventsCst)(nil), "protocol.FinishDissolveEventsCst")
	proto.RegisterType((*CheckActivityCst)(nil), "protocol.CheckActivityCst")
	proto.RegisterType((*PlayerCst)(nil), "protocol.PlayerCst")
	proto.RegisterType((*GetPlayerPublicInfoCst)(nil), "protocol.GetPlayerPublicInfoCst")
	proto.RegisterType((*GetFallenInfoCst)(nil), "protocol.GetFallenInfoCst")
	proto.RegisterType((*GetNpcTroopsCst)(nil), "protocol.GetNpcTroopsCst")
	proto.RegisterType((*GetPlayerTroopsCst)(nil), "protocol.GetPlayerTroopsCst")
	proto.RegisterType((*FeedBlocksCst)(nil), "protocol.FeedBlocksCst")
	proto.RegisterType((*MarchCst)(nil), "protocol.MarchCst")
	proto.RegisterType((*CancelMarchCst)(nil), "protocol.CancelMarchCst")
	proto.RegisterType((*CallbackTroopCst)(nil), "protocol.CallbackTroopCst")
	proto.RegisterType((*AbandonPointCst)(nil), "protocol.AbandonPointCst")
	proto.RegisterType((*RecruitMaxCst)(nil), "protocol.RecruitMaxCst")
	proto.RegisterType((*RecruitAllCst)(nil), "protocol.RecruitAllCst")
	proto.RegisterType((*CancelRecruitCst)(nil), "protocol.CancelRecruitCst")
	proto.RegisterType((*EditTroopCst)(nil), "protocol.EditTroopCst")
	proto.RegisterType((*CreateAllianceCst)(nil), "protocol.CreateAllianceCst")
	proto.RegisterType((*GetAllianceCst)(nil), "protocol.GetAllianceCst")
	proto.RegisterType((*GetAllianceMembersCst)(nil), "protocol.GetAllianceMembersCst")
	proto.RegisterType((*SearchAllianceCst)(nil), "protocol.SearchAllianceCst")
	proto.RegisterType((*GetAlliancesCst)(nil), "protocol.GetAlliancesCst")
	proto.RegisterType((*JoinAllianceCst)(nil), "protocol.JoinAllianceCst")
	proto.RegisterType((*RefuseJoinCst)(nil), "protocol.RefuseJoinCst")
	proto.RegisterType((*ApprovalJoinCst)(nil), "protocol.ApprovalJoinCst")
	proto.RegisterType((*KickMemberCst)(nil), "protocol.KickMemberCst")
	proto.RegisterType((*PromoteCst)(nil), "protocol.PromoteCst")
	proto.RegisterType((*SetAllianceCst)(nil), "protocol.SetAllianceCst")
	proto.RegisterType((*AddAllianceMarkCst)(nil), "protocol.AddAllianceMarkCst")
	proto.RegisterType((*DelAllianceMarkCst)(nil), "protocol.DelAllianceMarkCst")
	proto.RegisterType((*GetAllianceSlavesCst)(nil), "protocol.GetAllianceSlavesCst")
	proto.RegisterType((*PayLiberationCst)(nil), "protocol.PayLiberationCst")
	proto.RegisterType((*BuildCst)(nil), "protocol.BuildCst")
	proto.RegisterType((*UpgradeCst)(nil), "protocol.UpgradeCst")
	proto.RegisterType((*CancelBuildCst)(nil), "protocol.CancelBuildCst")
	proto.RegisterType((*GiveUpBuildingCst)(nil), "protocol.GiveUpBuildingCst")
	proto.RegisterType((*CancelGiveUpBuildingCst)(nil), "protocol.CancelGiveUpBuildingCst")
	proto.RegisterType((*GetRecentCoordByLevelCst)(nil), "protocol.GetRecentCoordByLevelCst")
	proto.RegisterType((*GetCanAddForceCoordCst)(nil), "protocol.GetCanAddForceCoordCst")
	proto.RegisterType((*GetRecentMonsterByLevelCst)(nil), "protocol.GetRecentMonsterByLevelCst")
	proto.RegisterType((*GetMonsterByCoordCst)(nil), "protocol.GetMonsterByCoordCst")
	proto.RegisterType((*GetDominationByCoordCst)(nil), "protocol.GetDominationByCoordCst")
	proto.RegisterType((*LevelUpCst)(nil), "protocol.LevelUpCst")
	proto.RegisterType((*LotteryCst)(nil), "protocol.LotteryCst")
	proto.RegisterType((*OpenChestCst)(nil), "protocol.OpenChestCst")
	proto.RegisterType((*GetTaskRewardCst)(nil), "protocol.GetTaskRewardCst")
	proto.RegisterType((*GetVitalityRewardCst)(nil), "protocol.GetVitalityRewardCst")
	proto.RegisterType((*GetChapterTaskRewardCst)(nil), "protocol.GetChapterTaskRewardCst")
	proto.RegisterType((*GetTaskDailyCst)(nil), "protocol.GetTaskDailyCst")
	proto.RegisterType((*GetChapterRewardCst)(nil), "protocol.GetChapterRewardCst")
	proto.RegisterType((*AllianceChatCst)(nil), "protocol.AllianceChatCst")
	proto.RegisterType((*SendAllianceMessageCst)(nil), "protocol.SendAllianceMessageCst")
	proto.RegisterType((*ReturnTroopImmediatelyCst)(nil), "protocol.ReturnTroopImmediatelyCst")
	proto.RegisterType((*GetForceRewardCst)(nil), "protocol.GetForceRewardCst")
	proto.RegisterType((*GetCapturePersonalPointsCst)(nil), "protocol.GetCapturePersonalPointsCst")
	proto.RegisterType((*LoginCst)(nil), "protocol.LoginCst")
	proto.RegisterType((*ExchangeTroopHeroCst)(nil), "protocol.ExchangeTroopHeroCst")
	proto.RegisterType((*GetDailyLimitExpiredCst)(nil), "protocol.GetDailyLimitExpiredCst")
	proto.RegisterType((*SetActivityCst)(nil), "protocol.SetActivityCst")
}

func init() { proto.RegisterFile("cast.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 1348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5f, 0x6f, 0xdb, 0x36,
	0x10, 0x47, 0x9c, 0xba, 0xb3, 0x2f, 0xff, 0xd5, 0xc4, 0x71, 0xd3, 0xae, 0x08, 0x38, 0x0c, 0x2d,
	0xb6, 0xa1, 0x03, 0xb2, 0x01, 0xc3, 0xd6, 0xb4, 0x80, 0x23, 0x3b, 0x5e, 0x3a, 0x3b, 0x35, 0x94,
	0xa4, 0x7d, 0xea, 0x03, 0x2d, 0x5d, 0x6c, 0xc2, 0xb2, 0xa8, 0x51, 0xb4, 0x1b, 0x3f, 0x6c, 0x1f,
	0x67, 0xdf, 0x62, 0xdf, 0x6d, 0x20, 0x29, 0xc9, 0xea, 0x20, 0x79, 0x71, 0x53, 0xec, 0xc9, 0xbc,
	0x3b, 0xde, 0xf1, 0xf8, 0xbb, 0x3f, 0x3c, 0x19, 0xc0, 0xa5, 0x91, 0x7c, 0x1e, 0x0a, 0x2e, 0xb9,
	0x55, 0xd1, 0x3f, 0x2e, 0xf7, 0x0f, 0xd6, 0xe4, 0x2c, 0xc4, 0xc8, 0xb0, 0x0f, 0xd6, 0x23, 0x29,
	0x26, 0x6e, 0xbc, 0x89, 0xd4, 0xa1, 0xe6, 0x60, 0xc4, 0x85, 0x6c, 0xf8, 0x3e, 0xa3, 0x81, 0x8b,
	0x0e, 0x0d, 0x46, 0x91, 0x1d, 0x49, 0x52, 0x83, 0x5d, 0x23, 0xe9, 0xf9, 0x74, 0x86, 0x22, 0xe5,
	0xef, 0xc3, 0x9e, 0xe1, 0x77, 0x79, 0x10, 0xc9, 0x8c, 0x60, 0x0f, 0x1e, 0xf4, 0x04, 0xf7, 0x26,
	0x2e, 0x2a, 0xf9, 0x44, 0xb8, 0xa8, 0xd9, 0x16, 0x6c, 0x9f, 0x73, 0xc9, 0xae, 0x67, 0xf6, 0x90,
	0x06, 0x03, 0xc3, 0x7b, 0x04, 0x0f, 0x4f, 0x59, 0xc0, 0xa2, 0x61, 0xa3, 0xef, 0x31, 0x97, 0x4a,
	0xc6, 0x83, 0xd6, 0x14, 0x03, 0x99, 0x1c, 0x6c, 0x84, 0x5d, 0x2a, 0xdc, 0xe1, 0x9c, 0x5f, 0x87,
	0x9a, 0xe1, 0x3b, 0xe8, 0x8a, 0x09, 0x93, 0x39, 0x1a, 0x27, 0x13, 0xe6, 0x7b, 0x39, 0x1a, 0x8d,
	0x3e, 0x0d, 0xbc, 0xec, 0x19, 0xfb, 0xb0, 0x97, 0xd8, 0x9a, 0xf2, 0x11, 0xce, 0x05, 0x0f, 0x61,
	0xdf, 0x08, 0x9a, 0x2c, 0x8a, 0xb8, 0x3f, 0xcd, 0x88, 0x2c, 0xd8, 0xb6, 0x87, 0xe8, 0x8e, 0x1a,
	0xae, 0x64, 0x53, 0x26, 0x67, 0x8a, 0xf7, 0x25, 0x54, 0x0d, 0x3c, 0x76, 0x24, 0xad, 0x6d, 0x58,
	0xed, 0x31, 0xaf, 0xbe, 0x72, 0x58, 0x7a, 0x56, 0x75, 0xd4, 0x92, 0x9c, 0x42, 0xad, 0x8d, 0x31,
	0x80, 0xbd, 0x49, 0xdf, 0x67, 0xee, 0x59, 0x70, 0xcd, 0x73, 0xf7, 0x5a, 0x07, 0x50, 0xb9, 0xa4,
	0x62, 0x80, 0xf2, 0xcc, 0xab, 0x97, 0x34, 0x3b, 0xa5, 0x49, 0x17, 0xb6, 0xdb, 0x28, 0x4f, 0xa9,
	0xef, 0x63, 0x50, 0x6c, 0xe1, 0x29, 0xdc, 0xb7, 0x39, 0x17, 0x5e, 0x54, 0x2f, 0x1d, 0xae, 0x3e,
	0x5b, 0x3b, 0xda, 0x7a, 0x9e, 0x64, 0xc0, 0x73, 0xcd, 0x77, 0x62, 0x31, 0x79, 0x0d, 0x5b, 0x6d,
	0x94, 0xe7, 0xa1, 0x7b, 0x29, 0x38, 0x0f, 0xa3, 0x7c, 0x6b, 0x5f, 0x43, 0x59, 0x6f, 0xd7, 0xce,
	0xe4, 0x18, 0x33, 0x52, 0x42, 0xc1, 0x4a, 0xaf, 0x78, 0x77, 0x73, 0x96, 0x05, 0xf7, 0x7a, 0x74,
	0x80, 0xf5, 0xd5, 0xc3, 0xd2, 0xb3, 0xb2, 0xa3, 0xd7, 0xe4, 0x05, 0x6c, 0x9c, 0x22, 0x7a, 0x27,
	0x3e, 0x77, 0x47, 0x05, 0xd6, 0xeb, 0xf0, 0xc5, 0x9b, 0xeb, 0xeb, 0x08, 0xa5, 0xb9, 0x7b, 0xd5,
	0x49, 0x48, 0xf2, 0x07, 0x54, 0x74, 0x1e, 0x15, 0xea, 0x69, 0xa7, 0x53, 0xcc, 0x13, 0xd2, 0x7a,
	0x0c, 0x55, 0xad, 0x77, 0x39, 0x0b, 0x13, 0x6f, 0xe6, 0x0c, 0x05, 0xb5, 0x09, 0x4e, 0xfd, 0x5e,
	0xfe, 0x75, 0x62, 0x31, 0x39, 0x82, 0x4d, 0x5b, 0x95, 0x95, 0xbf, 0xc0, 0x89, 0x4d, 0x28, 0xa5,
	0xe7, 0x97, 0xce, 0x3c, 0xf2, 0x23, 0x6c, 0xdb, 0xd4, 0xf7, 0xfb, 0xd4, 0x1d, 0x69, 0x6f, 0x6e,
	0xa7, 0xf5, 0x1a, 0xb6, 0xe2, 0x34, 0xef, 0x71, 0x16, 0xc8, 0x3b, 0x05, 0xf5, 0x1d, 0x6c, 0xc4,
	0x45, 0xd6, 0xa5, 0x37, 0xcb, 0x22, 0x77, 0x00, 0x95, 0x5f, 0x51, 0xf0, 0x73, 0x3a, 0x36, 0xc0,
	0x55, 0x9d, 0x94, 0x56, 0xa1, 0x8c, 0x0d, 0x37, 0x7c, 0x7f, 0x49, 0xc3, 0xe4, 0x95, 0xc2, 0x45,
	0x61, 0x19, 0x9b, 0x28, 0xd4, 0xd7, 0x35, 0x3b, 0xd7, 0x8f, 0x49, 0x72, 0x03, 0xeb, 0x2d, 0x8f,
	0xc9, 0x05, 0x98, 0x16, 0x5f, 0xea, 0x18, 0x36, 0xd4, 0x25, 0x7a, 0x3c, 0x62, 0xaa, 0x5b, 0x45,
	0xf5, 0x55, 0x5d, 0x62, 0xb5, 0x39, 0x80, 0x59, 0xb1, 0xf3, 0xf1, 0x66, 0xf2, 0xf7, 0x0a, 0xec,
	0xd8, 0x02, 0xa9, 0xc4, 0xa4, 0xcd, 0xe6, 0x9f, 0x6f, 0xc1, 0x3d, 0x0d, 0x9b, 0x39, 0x5c, 0xaf,
	0x15, 0xaf, 0x89, 0x91, 0x1b, 0x43, 0xa9, 0xd7, 0x56, 0x0d, 0xee, 0xb7, 0xc6, 0x7d, 0x1f, 0xc7,
	0x3a, 0xfd, 0xca, 0x4e, 0x4c, 0x29, 0xe8, 0x5f, 0x73, 0x16, 0xe8, 0x9c, 0x05, 0x2d, 0x49, 0x69,
	0xeb, 0x09, 0xc0, 0x29, 0x17, 0x2e, 0x76, 0xd8, 0x98, 0xc9, 0xfa, 0x9a, 0x96, 0x66, 0x38, 0x4a,
	0xb7, 0x43, 0x83, 0xc1, 0x44, 0x55, 0xdf, 0xba, 0xd1, 0x4d, 0x68, 0x72, 0x02, 0x9b, 0x6d, 0x94,
	0x8b, 0x7d, 0x7f, 0x02, 0x90, 0x6c, 0x48, 0xe1, 0xcb, 0x70, 0xc8, 0x07, 0xd8, 0xcb, 0xd8, 0xe8,
	0xe2, 0xb8, 0x8f, 0x22, 0xfa, 0x24, 0x53, 0x79, 0x4d, 0x42, 0x77, 0x00, 0xe1, 0xa1, 0x38, 0x99,
	0x69, 0x4c, 0x54, 0x07, 0x30, 0x24, 0xf9, 0x19, 0x76, 0x2e, 0x50, 0x55, 0xdf, 0xd2, 0xd8, 0x93,
	0x9f, 0x74, 0xa3, 0x4c, 0xf4, 0xa2, 0x42, 0x45, 0xed, 0x4d, 0x29, 0xd3, 0xb2, 0xde, 0xc3, 0x96,
	0x02, 0xfe, 0x4e, 0x88, 0xa9, 0x2b, 0x75, 0x31, 0x8a, 0x92, 0x9b, 0x56, 0x9d, 0x84, 0x24, 0xb6,
	0x2a, 0xa3, 0xeb, 0x49, 0x84, 0xea, 0x90, 0x7c, 0xe3, 0x87, 0xb0, 0xe6, 0xe0, 0xef, 0x13, 0x54,
	0x4f, 0x74, 0x6a, 0x3d, 0xcb, 0x22, 0x2d, 0xd8, 0x6a, 0x84, 0xa1, 0xe0, 0x53, 0xea, 0xdf, 0xc5,
	0xcc, 0x4b, 0xd8, 0xf8, 0x8d, 0xb9, 0x23, 0x13, 0xd0, 0xc2, 0xa7, 0xcd, 0x88, 0xe7, 0x4f, 0x5b,
	0x42, 0x93, 0x73, 0x80, 0x9e, 0xe0, 0x63, 0x2e, 0x71, 0x69, 0x5d, 0x85, 0xbc, 0xc3, 0xfd, 0x34,
	0x0f, 0xd4, 0x9a, 0xfc, 0xb5, 0x02, 0x9b, 0x17, 0xff, 0x95, 0xab, 0x49, 0x4d, 0x95, 0x72, 0x6b,
	0x6a, 0xf5, 0x7f, 0xa9, 0x29, 0x0a, 0x56, 0xc3, 0xf3, 0xd2, 0x7a, 0xa0, 0x62, 0x74, 0xd7, 0x87,
	0x33, 0xd3, 0x71, 0x4d, 0xfa, 0x76, 0xc1, 0x6a, 0xa2, 0xff, 0xb9, 0x8e, 0x20, 0xc7, 0xb0, 0x9b,
	0xa9, 0x86, 0x0b, 0x9f, 0x4e, 0x97, 0x29, 0x89, 0x3f, 0x61, 0xbb, 0x47, 0x67, 0x1d, 0xd6, 0x47,
	0xa1, 0x07, 0xbe, 0x42, 0xcd, 0x53, 0xce, 0xbd, 0x44, 0x53, 0xad, 0x55, 0x64, 0x3a, 0x13, 0x15,
	0xf2, 0x24, 0x32, 0x86, 0x52, 0xfc, 0x2e, 0x15, 0x7d, 0x1f, 0x93, 0x2e, 0x68, 0x28, 0x6b, 0x17,
	0xca, 0x17, 0x12, 0xd1, 0xaf, 0x97, 0x35, 0xdb, 0x10, 0xe4, 0x1d, 0x54, 0xf4, 0x78, 0x78, 0xfb,
	0xce, 0x9b, 0xc2, 0xb2, 0xba, 0x10, 0x96, 0x23, 0x80, 0xab, 0x70, 0x20, 0xa8, 0xb7, 0x44, 0x63,
	0x39, 0x4e, 0xc6, 0x82, 0x05, 0x2e, 0x15, 0x3f, 0x64, 0x67, 0xb0, 0xd3, 0x66, 0x53, 0xbc, 0x0a,
	0xb5, 0x36, 0x0b, 0x06, 0xf9, 0x06, 0x08, 0xac, 0x27, 0x1b, 0x32, 0x0e, 0x7c, 0xc4, 0x23, 0x2d,
	0xd8, 0x37, 0x8e, 0xdc, 0xc6, 0x60, 0xb1, 0x47, 0x6f, 0xa1, 0xde, 0x46, 0xe9, 0xa0, 0x8b, 0x81,
	0xd4, 0xa8, 0x9c, 0xcc, 0x3a, 0x38, 0xc5, 0x82, 0x27, 0x7e, 0x17, 0xca, 0x5a, 0x1a, 0x47, 0xd9,
	0x10, 0x0a, 0xa7, 0xcc, 0xb0, 0xa5, 0xd7, 0xe4, 0x1b, 0x3d, 0x40, 0xdb, 0x34, 0x68, 0x78, 0x9e,
	0xae, 0x2b, 0x6d, 0x3c, 0x7f, 0xd8, 0x6e, 0xc2, 0x41, 0xea, 0x43, 0xfc, 0x6d, 0xb2, 0xbc, 0x17,
	0xe4, 0x8d, 0x4e, 0xf2, 0x54, 0xbf, 0xf8, 0xbc, 0xdb, 0x56, 0x8d, 0x03, 0xfb, 0x6d, 0x94, 0x4d,
	0x3e, 0x66, 0x81, 0xce, 0xfb, 0xcf, 0x61, 0xf3, 0x17, 0x00, 0xed, 0xed, 0x55, 0x58, 0xd8, 0x34,
	0xd3, 0x11, 0xac, 0xf4, 0xaf, 0x11, 0xec, 0x18, 0xa0, 0xc3, 0xa5, 0x44, 0x31, 0xcb, 0xd7, 0x7d,
	0x0c, 0xd5, 0xb6, 0xe0, 0x93, 0x30, 0xa3, 0x3c, 0x67, 0x90, 0x57, 0xb0, 0xfe, 0x26, 0xc4, 0xc0,
	0x1e, 0x62, 0x24, 0x0b, 0xf5, 0xb5, 0x34, 0xab, 0x9f, 0x32, 0xc8, 0xb1, 0xfe, 0x92, 0xb9, 0xa4,
	0xd1, 0xc8, 0xc1, 0x0f, 0xb4, 0x08, 0x86, 0x9a, 0x1a, 0xaf, 0xa3, 0xd1, 0x59, 0xd2, 0x07, 0x62,
	0x8a, 0x34, 0x75, 0x70, 0xde, 0x32, 0x49, 0x7d, 0x26, 0x67, 0x8b, 0x2c, 0x1c, 0x40, 0xc5, 0x88,
	0x53, 0x1b, 0x29, 0x4d, 0x6c, 0x1d, 0x11, 0x7b, 0x48, 0x43, 0x89, 0xe2, 0x53, 0x5d, 0xf9, 0x4a,
	0x8f, 0x06, 0x8a, 0x68, 0x52, 0xe6, 0xe7, 0x63, 0x49, 0x9e, 0xc2, 0x83, 0xf9, 0x49, 0x0b, 0x4e,
	0x21, 0x2f, 0x61, 0x2b, 0x7d, 0xb1, 0x86, 0xb4, 0x78, 0xb2, 0xb5, 0x79, 0x20, 0x31, 0x90, 0x49,
	0xf9, 0xc5, 0x24, 0x69, 0x42, 0xed, 0x02, 0x83, 0xf9, 0x63, 0x62, 0xc6, 0x84, 0x65, 0xad, 0xb4,
	0xe1, 0xa1, 0x83, 0x72, 0x22, 0x02, 0x33, 0xf4, 0x8e, 0xc7, 0xe8, 0x31, 0x2a, 0xb1, 0xe0, 0x72,
	0x0b, 0x06, 0xf5, 0x17, 0xb0, 0xa3, 0x3e, 0x57, 0x55, 0xbd, 0x2e, 0x82, 0x36, 0xbf, 0x00, 0xbf,
	0x87, 0x47, 0xba, 0xe4, 0x43, 0x39, 0x11, 0xd8, 0x43, 0x11, 0xf1, 0x80, 0xfa, 0xfa, 0x93, 0x26,
	0xff, 0xb1, 0x21, 0x47, 0x50, 0xe9, 0xf0, 0x41, 0xd1, 0x00, 0xb3, 0x0b, 0xe5, 0x2e, 0x0d, 0x2f,
	0xce, 0xeb, 0xa5, 0xc3, 0x15, 0x75, 0x88, 0x26, 0xc8, 0x7b, 0xd8, 0x6d, 0xdd, 0xb8, 0xfa, 0x0f,
	0x09, 0xed, 0xb4, 0xaa, 0x8e, 0x7c, 0xfd, 0x1f, 0xf4, 0x13, 0x3f, 0xa6, 0x66, 0xea, 0x37, 0x1f,
	0xd6, 0x0f, 0xe6, 0x65, 0x99, 0xca, 0x9c, 0xcc, 0x36, 0xf2, 0xad, 0xa9, 0x79, 0x95, 0x18, 0x7a,
	0x10, 0x68, 0xdd, 0x84, 0x4c, 0x60, 0x41, 0xec, 0xbf, 0x33, 0x03, 0xcb, 0xfc, 0x5f, 0x05, 0x95,
	0xbc, 0x09, 0x19, 0x6f, 0x4c, 0xe9, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xe5, 0x7c, 0x4d,
	0xe2, 0x11, 0x00, 0x00,
}
