// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notify.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FeedBlocksNtf struct {
	Blocks           []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FeedBlocksNtf) Reset()                    { *m = FeedBlocksNtf{} }
func (m *FeedBlocksNtf) String() string            { return proto.CompactTextString(m) }
func (*FeedBlocksNtf) ProtoMessage()               {}
func (*FeedBlocksNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *FeedBlocksNtf) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type FeedBlockMonsterNtf struct {
	MonsterBlocks    []*MonsterBlock `protobuf:"bytes,1,rep,name=MonsterBlocks" json:"MonsterBlocks,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FeedBlockMonsterNtf) Reset()                    { *m = FeedBlockMonsterNtf{} }
func (m *FeedBlockMonsterNtf) String() string            { return proto.CompactTextString(m) }
func (*FeedBlockMonsterNtf) ProtoMessage()               {}
func (*FeedBlockMonsterNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *FeedBlockMonsterNtf) GetMonsterBlocks() []*MonsterBlock {
	if m != nil {
		return m.MonsterBlocks
	}
	return nil
}

type FeedBlockDominationNtf struct {
	BossBlocks       []*BossBlock `protobuf:"bytes,1,rep,name=BossBlocks" json:"BossBlocks,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FeedBlockDominationNtf) Reset()                    { *m = FeedBlockDominationNtf{} }
func (m *FeedBlockDominationNtf) String() string            { return proto.CompactTextString(m) }
func (*FeedBlockDominationNtf) ProtoMessage()               {}
func (*FeedBlockDominationNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *FeedBlockDominationNtf) GetBossBlocks() []*BossBlock {
	if m != nil {
		return m.BossBlocks
	}
	return nil
}

type FeedBlocksMarchesNtf struct {
	EventMarches     []*EventMarch `protobuf:"bytes,1,rep,name=EventMarches" json:"EventMarches,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FeedBlocksMarchesNtf) Reset()                    { *m = FeedBlocksMarchesNtf{} }
func (m *FeedBlocksMarchesNtf) String() string            { return proto.CompactTextString(m) }
func (*FeedBlocksMarchesNtf) ProtoMessage()               {}
func (*FeedBlocksMarchesNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *FeedBlocksMarchesNtf) GetEventMarches() []*EventMarch {
	if m != nil {
		return m.EventMarches
	}
	return nil
}

type ActivityNtf struct {
	Activity         []*Activity `protobuf:"bytes,1,rep,name=Activity" json:"Activity,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ActivityNtf) Reset()                    { *m = ActivityNtf{} }
func (m *ActivityNtf) String() string            { return proto.CompactTextString(m) }
func (*ActivityNtf) ProtoMessage()               {}
func (*ActivityNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *ActivityNtf) GetActivity() []*Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

type EventMarchNtf struct {
	EventMarch       *EventMarch `protobuf:"bytes,1,req,name=EventMarch" json:"EventMarch,omitempty"`
	Method           *string     `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *EventMarchNtf) Reset()                    { *m = EventMarchNtf{} }
func (m *EventMarchNtf) String() string            { return proto.CompactTextString(m) }
func (*EventMarchNtf) ProtoMessage()               {}
func (*EventMarchNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *EventMarchNtf) GetEventMarch() *EventMarch {
	if m != nil {
		return m.EventMarch
	}
	return nil
}

func (m *EventMarchNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type EventRecruitNtf struct {
	EventRecruit     *EventRecruit `protobuf:"bytes,1,req,name=EventRecruit" json:"EventRecruit,omitempty"`
	Method           *string       `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *EventRecruitNtf) Reset()                    { *m = EventRecruitNtf{} }
func (m *EventRecruitNtf) String() string            { return proto.CompactTextString(m) }
func (*EventRecruitNtf) ProtoMessage()               {}
func (*EventRecruitNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *EventRecruitNtf) GetEventRecruit() *EventRecruit {
	if m != nil {
		return m.EventRecruit
	}
	return nil
}

func (m *EventRecruitNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type EventAbandonNtf struct {
	EventAbandon     *EventAbandon `protobuf:"bytes,1,req,name=EventAbandon" json:"EventAbandon,omitempty"`
	Method           *string       `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *EventAbandonNtf) Reset()                    { *m = EventAbandonNtf{} }
func (m *EventAbandonNtf) String() string            { return proto.CompactTextString(m) }
func (*EventAbandonNtf) ProtoMessage()               {}
func (*EventAbandonNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *EventAbandonNtf) GetEventAbandon() *EventAbandon {
	if m != nil {
		return m.EventAbandon
	}
	return nil
}

func (m *EventAbandonNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type EventGiveUpNtf struct {
	EventGiveUp      *EventGiveUp `protobuf:"bytes,1,req,name=EventGiveUp" json:"EventGiveUp,omitempty"`
	Method           *string      `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *EventGiveUpNtf) Reset()                    { *m = EventGiveUpNtf{} }
func (m *EventGiveUpNtf) String() string            { return proto.CompactTextString(m) }
func (*EventGiveUpNtf) ProtoMessage()               {}
func (*EventGiveUpNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *EventGiveUpNtf) GetEventGiveUp() *EventGiveUp {
	if m != nil {
		return m.EventGiveUp
	}
	return nil
}

func (m *EventGiveUpNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type EventBuildNtf struct {
	EventBuild       *EventBuild `protobuf:"bytes,1,req,name=EventBuild" json:"EventBuild,omitempty"`
	Method           *string     `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *EventBuildNtf) Reset()                    { *m = EventBuildNtf{} }
func (m *EventBuildNtf) String() string            { return proto.CompactTextString(m) }
func (*EventBuildNtf) ProtoMessage()               {}
func (*EventBuildNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *EventBuildNtf) GetEventBuild() *EventBuild {
	if m != nil {
		return m.EventBuild
	}
	return nil
}

func (m *EventBuildNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type HeroesNtf struct {
	Heroes           []*Hero `protobuf:"bytes,1,rep,name=Heroes" json:"Heroes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeroesNtf) Reset()                    { *m = HeroesNtf{} }
func (m *HeroesNtf) String() string            { return proto.CompactTextString(m) }
func (*HeroesNtf) ProtoMessage()               {}
func (*HeroesNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *HeroesNtf) GetHeroes() []*Hero {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type PlayerPointNtf struct {
	Point            *Point  `protobuf:"bytes,1,req,name=Point" json:"Point,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerPointNtf) Reset()                    { *m = PlayerPointNtf{} }
func (m *PlayerPointNtf) String() string            { return proto.CompactTextString(m) }
func (*PlayerPointNtf) ProtoMessage()               {}
func (*PlayerPointNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *PlayerPointNtf) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *PlayerPointNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type FteStepNtf struct {
	Key              *string `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FteStepNtf) Reset()                    { *m = FteStepNtf{} }
func (m *FteStepNtf) String() string            { return proto.CompactTextString(m) }
func (*FteStepNtf) ProtoMessage()               {}
func (*FteStepNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *FteStepNtf) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type PlayerBuildingNtf struct {
	Building         *ElementBuilding `protobuf:"bytes,1,req,name=Building" json:"Building,omitempty"`
	Method           *string          `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	ElementType      *int32           `protobuf:"varint,3,req,name=ElementType" json:"ElementType,omitempty"`
	Resource         *ElementResource `protobuf:"bytes,4,req,name=Resource" json:"Resource,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PlayerBuildingNtf) Reset()                    { *m = PlayerBuildingNtf{} }
func (m *PlayerBuildingNtf) String() string            { return proto.CompactTextString(m) }
func (*PlayerBuildingNtf) ProtoMessage()               {}
func (*PlayerBuildingNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

func (m *PlayerBuildingNtf) GetBuilding() *ElementBuilding {
	if m != nil {
		return m.Building
	}
	return nil
}

func (m *PlayerBuildingNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *PlayerBuildingNtf) GetElementType() int32 {
	if m != nil && m.ElementType != nil {
		return *m.ElementType
	}
	return 0
}

func (m *PlayerBuildingNtf) GetResource() *ElementResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type ResourcesNtf struct {
	Resources        *Resources `protobuf:"bytes,1,req,name=Resources" json:"Resources,omitempty"`
	ChangedResources *Resources `protobuf:"bytes,2,req,name=ChangedResources" json:"ChangedResources,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ResourcesNtf) Reset()                    { *m = ResourcesNtf{} }
func (m *ResourcesNtf) String() string            { return proto.CompactTextString(m) }
func (*ResourcesNtf) ProtoMessage()               {}
func (*ResourcesNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{14} }

func (m *ResourcesNtf) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ResourcesNtf) GetChangedResources() *Resources {
	if m != nil {
		return m.ChangedResources
	}
	return nil
}

type ResourcesLimitNtf struct {
	ResourcesLimit   *Resources `protobuf:"bytes,1,req,name=ResourcesLimit" json:"ResourcesLimit,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ResourcesLimitNtf) Reset()                    { *m = ResourcesLimitNtf{} }
func (m *ResourcesLimitNtf) String() string            { return proto.CompactTextString(m) }
func (*ResourcesLimitNtf) ProtoMessage()               {}
func (*ResourcesLimitNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{15} }

func (m *ResourcesLimitNtf) GetResourcesLimit() *Resources {
	if m != nil {
		return m.ResourcesLimit
	}
	return nil
}

type CurrencyNtf struct {
	Currency         *Currency `protobuf:"bytes,1,req,name=Currency" json:"Currency,omitempty"`
	ChangedCurrency  *Currency `protobuf:"bytes,2,req,name=ChangedCurrency" json:"ChangedCurrency,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CurrencyNtf) Reset()                    { *m = CurrencyNtf{} }
func (m *CurrencyNtf) String() string            { return proto.CompactTextString(m) }
func (*CurrencyNtf) ProtoMessage()               {}
func (*CurrencyNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{16} }

func (m *CurrencyNtf) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *CurrencyNtf) GetChangedCurrency() *Currency {
	if m != nil {
		return m.ChangedCurrency
	}
	return nil
}

type NewBattleReportCountNtf struct {
	Count            *int32 `protobuf:"varint,1,req,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewBattleReportCountNtf) Reset()                    { *m = NewBattleReportCountNtf{} }
func (m *NewBattleReportCountNtf) String() string            { return proto.CompactTextString(m) }
func (*NewBattleReportCountNtf) ProtoMessage()               {}
func (*NewBattleReportCountNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{17} }

func (m *NewBattleReportCountNtf) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type NewSystemMessageCountNtf struct {
	Count            *int32 `protobuf:"varint,1,req,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewSystemMessageCountNtf) Reset()                    { *m = NewSystemMessageCountNtf{} }
func (m *NewSystemMessageCountNtf) String() string            { return proto.CompactTextString(m) }
func (*NewSystemMessageCountNtf) ProtoMessage()               {}
func (*NewSystemMessageCountNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{18} }

func (m *NewSystemMessageCountNtf) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type NewPersonalMessageCountNtf struct {
	Count            *int32  `protobuf:"varint,1,req,name=Count" json:"Count,omitempty"`
	From             *string `protobuf:"bytes,2,req,name=From" json:"From,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NewPersonalMessageCountNtf) Reset()                    { *m = NewPersonalMessageCountNtf{} }
func (m *NewPersonalMessageCountNtf) String() string            { return proto.CompactTextString(m) }
func (*NewPersonalMessageCountNtf) ProtoMessage()               {}
func (*NewPersonalMessageCountNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{19} }

func (m *NewPersonalMessageCountNtf) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *NewPersonalMessageCountNtf) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

type NewPersonalMessageNtf struct {
	PersonalMessage  *PersonalMessage `protobuf:"bytes,1,req,name=PersonalMessage" json:"PersonalMessage,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *NewPersonalMessageNtf) Reset()                    { *m = NewPersonalMessageNtf{} }
func (m *NewPersonalMessageNtf) String() string            { return proto.CompactTextString(m) }
func (*NewPersonalMessageNtf) ProtoMessage()               {}
func (*NewPersonalMessageNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{20} }

func (m *NewPersonalMessageNtf) GetPersonalMessage() *PersonalMessage {
	if m != nil {
		return m.PersonalMessage
	}
	return nil
}

type WorldChatNtf struct {
	Message          *ChatMessage `protobuf:"bytes,1,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *WorldChatNtf) Reset()                    { *m = WorldChatNtf{} }
func (m *WorldChatNtf) String() string            { return proto.CompactTextString(m) }
func (*WorldChatNtf) ProtoMessage()               {}
func (*WorldChatNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{21} }

func (m *WorldChatNtf) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type StateChatNtf struct {
	Message          *ChatMessage `protobuf:"bytes,1,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *StateChatNtf) Reset()                    { *m = StateChatNtf{} }
func (m *StateChatNtf) String() string            { return proto.CompactTextString(m) }
func (*StateChatNtf) ProtoMessage()               {}
func (*StateChatNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{22} }

func (m *StateChatNtf) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type TroopArrivedNtf struct {
	PointInfo        *PointInfo    `protobuf:"bytes,1,req,name=PointInfo" json:"PointInfo,omitempty"`
	HasBattle        *bool         `protobuf:"varint,2,req,name=HasBattle" json:"HasBattle,omitempty"`
	IsWin            *bool         `protobuf:"varint,3,req,name=IsWin" json:"IsWin,omitempty"`
	IsOccupied       *bool         `protobuf:"varint,4,req,name=IsOccupied" json:"IsOccupied,omitempty"`
	ReportId         *string       `protobuf:"bytes,5,req,name=ReportId" json:"ReportId,omitempty"`
	TroopName        *string       `protobuf:"bytes,6,req,name=TroopName" json:"TroopName,omitempty"`
	Reward           *CommonReward `protobuf:"bytes,7,req,name=Reward" json:"Reward,omitempty"`
	Resources        *Resources    `protobuf:"bytes,8,req,name=Resources" json:"Resources,omitempty"`
	Currency         *Currency     `protobuf:"bytes,9,req,name=Currency" json:"Currency,omitempty"`
	BattleTimes      *int32        `protobuf:"varint,10,req,name=BattleTimes" json:"BattleTimes,omitempty"`
	DefenderName     *string       `protobuf:"bytes,11,req,name=DefenderName" json:"DefenderName,omitempty"`
	DefenderAvatar   *int32        `protobuf:"varint,12,req,name=DefenderAvatar" json:"DefenderAvatar,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *TroopArrivedNtf) Reset()                    { *m = TroopArrivedNtf{} }
func (m *TroopArrivedNtf) String() string            { return proto.CompactTextString(m) }
func (*TroopArrivedNtf) ProtoMessage()               {}
func (*TroopArrivedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{23} }

func (m *TroopArrivedNtf) GetPointInfo() *PointInfo {
	if m != nil {
		return m.PointInfo
	}
	return nil
}

func (m *TroopArrivedNtf) GetHasBattle() bool {
	if m != nil && m.HasBattle != nil {
		return *m.HasBattle
	}
	return false
}

func (m *TroopArrivedNtf) GetIsWin() bool {
	if m != nil && m.IsWin != nil {
		return *m.IsWin
	}
	return false
}

func (m *TroopArrivedNtf) GetIsOccupied() bool {
	if m != nil && m.IsOccupied != nil {
		return *m.IsOccupied
	}
	return false
}

func (m *TroopArrivedNtf) GetReportId() string {
	if m != nil && m.ReportId != nil {
		return *m.ReportId
	}
	return ""
}

func (m *TroopArrivedNtf) GetTroopName() string {
	if m != nil && m.TroopName != nil {
		return *m.TroopName
	}
	return ""
}

func (m *TroopArrivedNtf) GetReward() *CommonReward {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *TroopArrivedNtf) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *TroopArrivedNtf) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *TroopArrivedNtf) GetBattleTimes() int32 {
	if m != nil && m.BattleTimes != nil {
		return *m.BattleTimes
	}
	return 0
}

func (m *TroopArrivedNtf) GetDefenderName() string {
	if m != nil && m.DefenderName != nil {
		return *m.DefenderName
	}
	return ""
}

func (m *TroopArrivedNtf) GetDefenderAvatar() int32 {
	if m != nil && m.DefenderAvatar != nil {
		return *m.DefenderAvatar
	}
	return 0
}

type FieldFirstDownNtf struct {
	FieldFirstDown   *FieldFirstDown `protobuf:"bytes,1,req,name=FieldFirstDown" json:"FieldFirstDown,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *FieldFirstDownNtf) Reset()                    { *m = FieldFirstDownNtf{} }
func (m *FieldFirstDownNtf) String() string            { return proto.CompactTextString(m) }
func (*FieldFirstDownNtf) ProtoMessage()               {}
func (*FieldFirstDownNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{24} }

func (m *FieldFirstDownNtf) GetFieldFirstDown() *FieldFirstDown {
	if m != nil {
		return m.FieldFirstDown
	}
	return nil
}

type NewTroopNtf struct {
	Troop            *Troop `protobuf:"bytes,1,req,name=Troop" json:"Troop,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewTroopNtf) Reset()                    { *m = NewTroopNtf{} }
func (m *NewTroopNtf) String() string            { return proto.CompactTextString(m) }
func (*NewTroopNtf) ProtoMessage()               {}
func (*NewTroopNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{25} }

func (m *NewTroopNtf) GetTroop() *Troop {
	if m != nil {
		return m.Troop
	}
	return nil
}

type TroopNtf struct {
	Troop            *Troop `protobuf:"bytes,1,req,name=Troop" json:"Troop,omitempty"`
	Src              *Coord `protobuf:"bytes,2,req,name=Src" json:"Src,omitempty"`
	Dst              *Coord `protobuf:"bytes,3,req,name=Dst" json:"Dst,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TroopNtf) Reset()                    { *m = TroopNtf{} }
func (m *TroopNtf) String() string            { return proto.CompactTextString(m) }
func (*TroopNtf) ProtoMessage()               {}
func (*TroopNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{26} }

func (m *TroopNtf) GetTroop() *Troop {
	if m != nil {
		return m.Troop
	}
	return nil
}

func (m *TroopNtf) GetSrc() *Coord {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *TroopNtf) GetDst() *Coord {
	if m != nil {
		return m.Dst
	}
	return nil
}

type ForceNtf struct {
	Force            *int32 `protobuf:"varint,1,req,name=Force" json:"Force,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ForceNtf) Reset()                    { *m = ForceNtf{} }
func (m *ForceNtf) String() string            { return proto.CompactTextString(m) }
func (*ForceNtf) ProtoMessage()               {}
func (*ForceNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{27} }

func (m *ForceNtf) GetForce() int32 {
	if m != nil && m.Force != nil {
		return *m.Force
	}
	return 0
}

type NewTasksCountNtf struct {
	Count            *int32 `protobuf:"varint,1,req,name=Count" json:"Count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NewTasksCountNtf) Reset()                    { *m = NewTasksCountNtf{} }
func (m *NewTasksCountNtf) String() string            { return proto.CompactTextString(m) }
func (*NewTasksCountNtf) ProtoMessage()               {}
func (*NewTasksCountNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{28} }

func (m *NewTasksCountNtf) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type ChapterTaskChangeNtf struct {
	TaskId           *int32 `protobuf:"varint,1,req,name=TaskId" json:"TaskId,omitempty"`
	Value            *int32 `protobuf:"varint,2,req,name=Value" json:"Value,omitempty"`
	IsDone           *bool  `protobuf:"varint,3,req,name=IsDone" json:"IsDone,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChapterTaskChangeNtf) Reset()                    { *m = ChapterTaskChangeNtf{} }
func (m *ChapterTaskChangeNtf) String() string            { return proto.CompactTextString(m) }
func (*ChapterTaskChangeNtf) ProtoMessage()               {}
func (*ChapterTaskChangeNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{29} }

func (m *ChapterTaskChangeNtf) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *ChapterTaskChangeNtf) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ChapterTaskChangeNtf) GetIsDone() bool {
	if m != nil && m.IsDone != nil {
		return *m.IsDone
	}
	return false
}

type TaskChangeNtf struct {
	TaskId           *int32 `protobuf:"varint,1,req,name=TaskId" json:"TaskId,omitempty"`
	Value            *int32 `protobuf:"varint,2,req,name=Value" json:"Value,omitempty"`
	IsDone           *bool  `protobuf:"varint,3,req,name=IsDone" json:"IsDone,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TaskChangeNtf) Reset()                    { *m = TaskChangeNtf{} }
func (m *TaskChangeNtf) String() string            { return proto.CompactTextString(m) }
func (*TaskChangeNtf) ProtoMessage()               {}
func (*TaskChangeNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{30} }

func (m *TaskChangeNtf) GetTaskId() int32 {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return 0
}

func (m *TaskChangeNtf) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *TaskChangeNtf) GetIsDone() bool {
	if m != nil && m.IsDone != nil {
		return *m.IsDone
	}
	return false
}

type PointLimitNtf struct {
	PointLimit       *int32 `protobuf:"varint,1,req,name=PointLimit" json:"PointLimit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PointLimitNtf) Reset()                    { *m = PointLimitNtf{} }
func (m *PointLimitNtf) String() string            { return proto.CompactTextString(m) }
func (*PointLimitNtf) ProtoMessage()               {}
func (*PointLimitNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{31} }

func (m *PointLimitNtf) GetPointLimit() int32 {
	if m != nil && m.PointLimit != nil {
		return *m.PointLimit
	}
	return 0
}

type TreasureMapNtf struct {
	TreasureMap      *TreasureMap `protobuf:"bytes,1,req,name=TreasureMap" json:"TreasureMap,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TreasureMapNtf) Reset()                    { *m = TreasureMapNtf{} }
func (m *TreasureMapNtf) String() string            { return proto.CompactTextString(m) }
func (*TreasureMapNtf) ProtoMessage()               {}
func (*TreasureMapNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{32} }

func (m *TreasureMapNtf) GetTreasureMap() *TreasureMap {
	if m != nil {
		return m.TreasureMap
	}
	return nil
}

type AllMarksNtf struct {
	Marks            []*Mark `protobuf:"bytes,1,rep,name=Marks" json:"Marks,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllMarksNtf) Reset()                    { *m = AllMarksNtf{} }
func (m *AllMarksNtf) String() string            { return proto.CompactTextString(m) }
func (*AllMarksNtf) ProtoMessage()               {}
func (*AllMarksNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{33} }

func (m *AllMarksNtf) GetMarks() []*Mark {
	if m != nil {
		return m.Marks
	}
	return nil
}

type AllianceMarkNtf struct {
	Mark             *Mark   `protobuf:"bytes,1,req,name=Mark" json:"Mark,omitempty"`
	Method           *string `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllianceMarkNtf) Reset()                    { *m = AllianceMarkNtf{} }
func (m *AllianceMarkNtf) String() string            { return proto.CompactTextString(m) }
func (*AllianceMarkNtf) ProtoMessage()               {}
func (*AllianceMarkNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{34} }

func (m *AllianceMarkNtf) GetMark() *Mark {
	if m != nil {
		return m.Mark
	}
	return nil
}

func (m *AllianceMarkNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type AllianceMarksNtf struct {
	Marks            []*Mark `protobuf:"bytes,1,rep,name=Marks" json:"Marks,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllianceMarksNtf) Reset()                    { *m = AllianceMarksNtf{} }
func (m *AllianceMarksNtf) String() string            { return proto.CompactTextString(m) }
func (*AllianceMarksNtf) ProtoMessage()               {}
func (*AllianceMarksNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{35} }

func (m *AllianceMarksNtf) GetMarks() []*Mark {
	if m != nil {
		return m.Marks
	}
	return nil
}

type RelationNtf struct {
	AllianceId         *string `protobuf:"bytes,1,req,name=AllianceId" json:"AllianceId,omitempty"`
	AllianceName       *string `protobuf:"bytes,2,req,name=AllianceName" json:"AllianceName,omitempty"`
	AllianceRole       *int32  `protobuf:"varint,3,req,name=AllianceRole" json:"AllianceRole,omitempty"`
	MasterAllianceId   *string `protobuf:"bytes,4,req,name=MasterAllianceId" json:"MasterAllianceId,omitempty"`
	MasterAllianceName *string `protobuf:"bytes,5,req,name=MasterAllianceName" json:"MasterAllianceName,omitempty"`
	QuitTimestamp      *int64  `protobuf:"varint,6,req,name=QuitTimestamp" json:"QuitTimestamp,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *RelationNtf) Reset()                    { *m = RelationNtf{} }
func (m *RelationNtf) String() string            { return proto.CompactTextString(m) }
func (*RelationNtf) ProtoMessage()               {}
func (*RelationNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{36} }

func (m *RelationNtf) GetAllianceId() string {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return ""
}

func (m *RelationNtf) GetAllianceName() string {
	if m != nil && m.AllianceName != nil {
		return *m.AllianceName
	}
	return ""
}

func (m *RelationNtf) GetAllianceRole() int32 {
	if m != nil && m.AllianceRole != nil {
		return *m.AllianceRole
	}
	return 0
}

func (m *RelationNtf) GetMasterAllianceId() string {
	if m != nil && m.MasterAllianceId != nil {
		return *m.MasterAllianceId
	}
	return ""
}

func (m *RelationNtf) GetMasterAllianceName() string {
	if m != nil && m.MasterAllianceName != nil {
		return *m.MasterAllianceName
	}
	return ""
}

func (m *RelationNtf) GetQuitTimestamp() int64 {
	if m != nil && m.QuitTimestamp != nil {
		return *m.QuitTimestamp
	}
	return 0
}

type AllianceMessageNtf struct {
	Message          *AllianceMessage `protobuf:"bytes,1,req,name=Message" json:"Message,omitempty"`
	Method           *string          `protobuf:"bytes,2,req,name=Method" json:"Method,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AllianceMessageNtf) Reset()                    { *m = AllianceMessageNtf{} }
func (m *AllianceMessageNtf) String() string            { return proto.CompactTextString(m) }
func (*AllianceMessageNtf) ProtoMessage()               {}
func (*AllianceMessageNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{37} }

func (m *AllianceMessageNtf) GetMessage() *AllianceMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *AllianceMessageNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

type FieldFirstDownRewardNtf struct {
	Level            *int32        `protobuf:"varint,1,req,name=Level" json:"Level,omitempty"`
	Reward           *CommonReward `protobuf:"bytes,2,opt,name=Reward" json:"Reward,omitempty"`
	Resources        *Resources    `protobuf:"bytes,3,req,name=Resources" json:"Resources,omitempty"`
	Currency         *Currency     `protobuf:"bytes,4,req,name=Currency" json:"Currency,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FieldFirstDownRewardNtf) Reset()                    { *m = FieldFirstDownRewardNtf{} }
func (m *FieldFirstDownRewardNtf) String() string            { return proto.CompactTextString(m) }
func (*FieldFirstDownRewardNtf) ProtoMessage()               {}
func (*FieldFirstDownRewardNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{38} }

func (m *FieldFirstDownRewardNtf) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *FieldFirstDownRewardNtf) GetReward() *CommonReward {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *FieldFirstDownRewardNtf) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *FieldFirstDownRewardNtf) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type EventMarchesNtf struct {
	EventMarches     []*EventMarch `protobuf:"bytes,1,rep,name=EventMarches" json:"EventMarches,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *EventMarchesNtf) Reset()                    { *m = EventMarchesNtf{} }
func (m *EventMarchesNtf) String() string            { return proto.CompactTextString(m) }
func (*EventMarchesNtf) ProtoMessage()               {}
func (*EventMarchesNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{39} }

func (m *EventMarchesNtf) GetEventMarches() []*EventMarch {
	if m != nil {
		return m.EventMarches
	}
	return nil
}

type ChestsNtf struct {
	Chests           []*Chest `protobuf:"bytes,1,rep,name=Chests" json:"Chests,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ChestsNtf) Reset()                    { *m = ChestsNtf{} }
func (m *ChestsNtf) String() string            { return proto.CompactTextString(m) }
func (*ChestsNtf) ProtoMessage()               {}
func (*ChestsNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{40} }

func (m *ChestsNtf) GetChests() []*Chest {
	if m != nil {
		return m.Chests
	}
	return nil
}

type DailyLimitNtf struct {
	Limit            *DailyLimit `protobuf:"bytes,1,req,name=Limit" json:"Limit,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *DailyLimitNtf) Reset()                    { *m = DailyLimitNtf{} }
func (m *DailyLimitNtf) String() string            { return proto.CompactTextString(m) }
func (*DailyLimitNtf) ProtoMessage()               {}
func (*DailyLimitNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{41} }

func (m *DailyLimitNtf) GetLimit() *DailyLimit {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ResourcesProductionNtf struct {
	Resources         *Resources `protobuf:"bytes,1,req,name=Resources" json:"Resources,omitempty"`
	BuildingResources *Resources `protobuf:"bytes,2,req,name=BuildingResources" json:"BuildingResources,omitempty"`
	NpcResources      *Resources `protobuf:"bytes,3,req,name=NpcResources" json:"NpcResources,omitempty"`
	AllResources      *Resources `protobuf:"bytes,4,req,name=AllResources" json:"AllResources,omitempty"`
	TributeGoldBonus  *int32     `protobuf:"varint,5,req,name=TributeGoldBonus" json:"TributeGoldBonus,omitempty"`
	XXX_unrecognized  []byte     `json:"-"`
}

func (m *ResourcesProductionNtf) Reset()                    { *m = ResourcesProductionNtf{} }
func (m *ResourcesProductionNtf) String() string            { return proto.CompactTextString(m) }
func (*ResourcesProductionNtf) ProtoMessage()               {}
func (*ResourcesProductionNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{42} }

func (m *ResourcesProductionNtf) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *ResourcesProductionNtf) GetBuildingResources() *Resources {
	if m != nil {
		return m.BuildingResources
	}
	return nil
}

func (m *ResourcesProductionNtf) GetNpcResources() *Resources {
	if m != nil {
		return m.NpcResources
	}
	return nil
}

func (m *ResourcesProductionNtf) GetAllResources() *Resources {
	if m != nil {
		return m.AllResources
	}
	return nil
}

func (m *ResourcesProductionNtf) GetTributeGoldBonus() int32 {
	if m != nil && m.TributeGoldBonus != nil {
		return *m.TributeGoldBonus
	}
	return 0
}

type FteNtf struct {
	IsFinished       *bool  `protobuf:"varint,1,req,name=IsFinished" json:"IsFinished,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FteNtf) Reset()                    { *m = FteNtf{} }
func (m *FteNtf) String() string            { return proto.CompactTextString(m) }
func (*FteNtf) ProtoMessage()               {}
func (*FteNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{43} }

func (m *FteNtf) GetIsFinished() bool {
	if m != nil && m.IsFinished != nil {
		return *m.IsFinished
	}
	return false
}

type AlertsNtf struct {
	Coords           []*Coord `protobuf:"bytes,1,rep,name=Coords" json:"Coords,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *AlertsNtf) Reset()                    { *m = AlertsNtf{} }
func (m *AlertsNtf) String() string            { return proto.CompactTextString(m) }
func (*AlertsNtf) ProtoMessage()               {}
func (*AlertsNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{44} }

func (m *AlertsNtf) GetCoords() []*Coord {
	if m != nil {
		return m.Coords
	}
	return nil
}

type ResourcesCollectedNtf struct {
	ResourcesCollected *ResourcesCollected `protobuf:"bytes,1,req,name=ResourcesCollected" json:"ResourcesCollected,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *ResourcesCollectedNtf) Reset()                    { *m = ResourcesCollectedNtf{} }
func (m *ResourcesCollectedNtf) String() string            { return proto.CompactTextString(m) }
func (*ResourcesCollectedNtf) ProtoMessage()               {}
func (*ResourcesCollectedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{45} }

func (m *ResourcesCollectedNtf) GetResourcesCollected() *ResourcesCollected {
	if m != nil {
		return m.ResourcesCollected
	}
	return nil
}

type CurrencyCollectedNtf struct {
	CurrencyCollected *CurrencyCollected `protobuf:"bytes,1,req,name=CurrencyCollected" json:"CurrencyCollected,omitempty"`
	XXX_unrecognized  []byte             `json:"-"`
}

func (m *CurrencyCollectedNtf) Reset()                    { *m = CurrencyCollectedNtf{} }
func (m *CurrencyCollectedNtf) String() string            { return proto.CompactTextString(m) }
func (*CurrencyCollectedNtf) ProtoMessage()               {}
func (*CurrencyCollectedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{46} }

func (m *CurrencyCollectedNtf) GetCurrencyCollected() *CurrencyCollected {
	if m != nil {
		return m.CurrencyCollected
	}
	return nil
}

type PaymentSuccessNtf struct {
	IsOK             *bool  `protobuf:"varint,1,req,name=IsOK" json:"IsOK,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PaymentSuccessNtf) Reset()                    { *m = PaymentSuccessNtf{} }
func (m *PaymentSuccessNtf) String() string            { return proto.CompactTextString(m) }
func (*PaymentSuccessNtf) ProtoMessage()               {}
func (*PaymentSuccessNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{47} }

func (m *PaymentSuccessNtf) GetIsOK() bool {
	if m != nil && m.IsOK != nil {
		return *m.IsOK
	}
	return false
}

type TroopHasBeenAttackedNtf struct {
	TroopName        *string `protobuf:"bytes,1,req,name=TroopName" json:"TroopName,omitempty"`
	AttackerName     *string `protobuf:"bytes,2,req,name=AttackerName" json:"AttackerName,omitempty"`
	AttackerAvatar   *int32  `protobuf:"varint,3,req,name=AttackerAvatar" json:"AttackerAvatar,omitempty"`
	DefenderWin      *bool   `protobuf:"varint,4,req,name=DefenderWin" json:"DefenderWin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TroopHasBeenAttackedNtf) Reset()                    { *m = TroopHasBeenAttackedNtf{} }
func (m *TroopHasBeenAttackedNtf) String() string            { return proto.CompactTextString(m) }
func (*TroopHasBeenAttackedNtf) ProtoMessage()               {}
func (*TroopHasBeenAttackedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{48} }

func (m *TroopHasBeenAttackedNtf) GetTroopName() string {
	if m != nil && m.TroopName != nil {
		return *m.TroopName
	}
	return ""
}

func (m *TroopHasBeenAttackedNtf) GetAttackerName() string {
	if m != nil && m.AttackerName != nil {
		return *m.AttackerName
	}
	return ""
}

func (m *TroopHasBeenAttackedNtf) GetAttackerAvatar() int32 {
	if m != nil && m.AttackerAvatar != nil {
		return *m.AttackerAvatar
	}
	return 0
}

func (m *TroopHasBeenAttackedNtf) GetDefenderWin() bool {
	if m != nil && m.DefenderWin != nil {
		return *m.DefenderWin
	}
	return false
}

type MiniMapAllyCoordsNtf struct {
	Method           *string  `protobuf:"bytes,1,req,name=Method" json:"Method,omitempty"`
	Coords           []*Coord `protobuf:"bytes,2,rep,name=Coords" json:"Coords,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MiniMapAllyCoordsNtf) Reset()                    { *m = MiniMapAllyCoordsNtf{} }
func (m *MiniMapAllyCoordsNtf) String() string            { return proto.CompactTextString(m) }
func (*MiniMapAllyCoordsNtf) ProtoMessage()               {}
func (*MiniMapAllyCoordsNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{49} }

func (m *MiniMapAllyCoordsNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *MiniMapAllyCoordsNtf) GetCoords() []*Coord {
	if m != nil {
		return m.Coords
	}
	return nil
}

type MiniMapAllianceCoordsNtf struct {
	Method           *string               `protobuf:"bytes,1,req,name=Method" json:"Method,omitempty"`
	Points           []*AllianceOwnedPoint `protobuf:"bytes,2,rep,name=Points" json:"Points,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *MiniMapAllianceCoordsNtf) Reset()                    { *m = MiniMapAllianceCoordsNtf{} }
func (m *MiniMapAllianceCoordsNtf) String() string            { return proto.CompactTextString(m) }
func (*MiniMapAllianceCoordsNtf) ProtoMessage()               {}
func (*MiniMapAllianceCoordsNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{50} }

func (m *MiniMapAllianceCoordsNtf) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *MiniMapAllianceCoordsNtf) GetPoints() []*AllianceOwnedPoint {
	if m != nil {
		return m.Points
	}
	return nil
}

type AllianceInfosNtf struct {
	Infos            []*AllianceBasicInfo `protobuf:"bytes,1,rep,name=Infos" json:"Infos,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AllianceInfosNtf) Reset()                    { *m = AllianceInfosNtf{} }
func (m *AllianceInfosNtf) String() string            { return proto.CompactTextString(m) }
func (*AllianceInfosNtf) ProtoMessage()               {}
func (*AllianceInfosNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{51} }

func (m *AllianceInfosNtf) GetInfos() []*AllianceBasicInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type ShortIdNtf struct {
	ShortId          *string `protobuf:"bytes,1,req,name=ShortId" json:"ShortId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShortIdNtf) Reset()                    { *m = ShortIdNtf{} }
func (m *ShortIdNtf) String() string            { return proto.CompactTextString(m) }
func (*ShortIdNtf) ProtoMessage()               {}
func (*ShortIdNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{52} }

func (m *ShortIdNtf) GetShortId() string {
	if m != nil && m.ShortId != nil {
		return *m.ShortId
	}
	return ""
}

// 充值奖励可领取
type RechargeRewardNtf struct {
	Level            *int32   `protobuf:"varint,1,req,name=Level" json:"Level,omitempty"`
	Amount           *float32 `protobuf:"fixed32,2,req,name=Amount" json:"Amount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RechargeRewardNtf) Reset()                    { *m = RechargeRewardNtf{} }
func (m *RechargeRewardNtf) String() string            { return proto.CompactTextString(m) }
func (*RechargeRewardNtf) ProtoMessage()               {}
func (*RechargeRewardNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{53} }

func (m *RechargeRewardNtf) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *RechargeRewardNtf) GetAmount() float32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*FeedBlocksNtf)(nil), "protocol.FeedBlocksNtf")
	proto.RegisterType((*FeedBlockMonsterNtf)(nil), "protocol.FeedBlockMonsterNtf")
	proto.RegisterType((*FeedBlockDominationNtf)(nil), "protocol.FeedBlockDominationNtf")
	proto.RegisterType((*FeedBlocksMarchesNtf)(nil), "protocol.FeedBlocksMarchesNtf")
	proto.RegisterType((*ActivityNtf)(nil), "protocol.ActivityNtf")
	proto.RegisterType((*EventMarchNtf)(nil), "protocol.EventMarchNtf")
	proto.RegisterType((*EventRecruitNtf)(nil), "protocol.EventRecruitNtf")
	proto.RegisterType((*EventAbandonNtf)(nil), "protocol.EventAbandonNtf")
	proto.RegisterType((*EventGiveUpNtf)(nil), "protocol.EventGiveUpNtf")
	proto.RegisterType((*EventBuildNtf)(nil), "protocol.EventBuildNtf")
	proto.RegisterType((*HeroesNtf)(nil), "protocol.HeroesNtf")
	proto.RegisterType((*PlayerPointNtf)(nil), "protocol.PlayerPointNtf")
	proto.RegisterType((*FteStepNtf)(nil), "protocol.FteStepNtf")
	proto.RegisterType((*PlayerBuildingNtf)(nil), "protocol.PlayerBuildingNtf")
	proto.RegisterType((*ResourcesNtf)(nil), "protocol.ResourcesNtf")
	proto.RegisterType((*ResourcesLimitNtf)(nil), "protocol.ResourcesLimitNtf")
	proto.RegisterType((*CurrencyNtf)(nil), "protocol.CurrencyNtf")
	proto.RegisterType((*NewBattleReportCountNtf)(nil), "protocol.NewBattleReportCountNtf")
	proto.RegisterType((*NewSystemMessageCountNtf)(nil), "protocol.NewSystemMessageCountNtf")
	proto.RegisterType((*NewPersonalMessageCountNtf)(nil), "protocol.NewPersonalMessageCountNtf")
	proto.RegisterType((*NewPersonalMessageNtf)(nil), "protocol.NewPersonalMessageNtf")
	proto.RegisterType((*WorldChatNtf)(nil), "protocol.WorldChatNtf")
	proto.RegisterType((*StateChatNtf)(nil), "protocol.StateChatNtf")
	proto.RegisterType((*TroopArrivedNtf)(nil), "protocol.TroopArrivedNtf")
	proto.RegisterType((*FieldFirstDownNtf)(nil), "protocol.FieldFirstDownNtf")
	proto.RegisterType((*NewTroopNtf)(nil), "protocol.NewTroopNtf")
	proto.RegisterType((*TroopNtf)(nil), "protocol.TroopNtf")
	proto.RegisterType((*ForceNtf)(nil), "protocol.ForceNtf")
	proto.RegisterType((*NewTasksCountNtf)(nil), "protocol.NewTasksCountNtf")
	proto.RegisterType((*ChapterTaskChangeNtf)(nil), "protocol.ChapterTaskChangeNtf")
	proto.RegisterType((*TaskChangeNtf)(nil), "protocol.TaskChangeNtf")
	proto.RegisterType((*PointLimitNtf)(nil), "protocol.PointLimitNtf")
	proto.RegisterType((*TreasureMapNtf)(nil), "protocol.TreasureMapNtf")
	proto.RegisterType((*AllMarksNtf)(nil), "protocol.AllMarksNtf")
	proto.RegisterType((*AllianceMarkNtf)(nil), "protocol.AllianceMarkNtf")
	proto.RegisterType((*AllianceMarksNtf)(nil), "protocol.AllianceMarksNtf")
	proto.RegisterType((*RelationNtf)(nil), "protocol.RelationNtf")
	proto.RegisterType((*AllianceMessageNtf)(nil), "protocol.AllianceMessageNtf")
	proto.RegisterType((*FieldFirstDownRewardNtf)(nil), "protocol.FieldFirstDownRewardNtf")
	proto.RegisterType((*EventMarchesNtf)(nil), "protocol.EventMarchesNtf")
	proto.RegisterType((*ChestsNtf)(nil), "protocol.ChestsNtf")
	proto.RegisterType((*DailyLimitNtf)(nil), "protocol.DailyLimitNtf")
	proto.RegisterType((*ResourcesProductionNtf)(nil), "protocol.ResourcesProductionNtf")
	proto.RegisterType((*FteNtf)(nil), "protocol.FteNtf")
	proto.RegisterType((*AlertsNtf)(nil), "protocol.AlertsNtf")
	proto.RegisterType((*ResourcesCollectedNtf)(nil), "protocol.ResourcesCollectedNtf")
	proto.RegisterType((*CurrencyCollectedNtf)(nil), "protocol.CurrencyCollectedNtf")
	proto.RegisterType((*PaymentSuccessNtf)(nil), "protocol.PaymentSuccessNtf")
	proto.RegisterType((*TroopHasBeenAttackedNtf)(nil), "protocol.TroopHasBeenAttackedNtf")
	proto.RegisterType((*MiniMapAllyCoordsNtf)(nil), "protocol.MiniMapAllyCoordsNtf")
	proto.RegisterType((*MiniMapAllianceCoordsNtf)(nil), "protocol.MiniMapAllianceCoordsNtf")
	proto.RegisterType((*AllianceInfosNtf)(nil), "protocol.AllianceInfosNtf")
	proto.RegisterType((*ShortIdNtf)(nil), "protocol.ShortIdNtf")
	proto.RegisterType((*RechargeRewardNtf)(nil), "protocol.RechargeRewardNtf")
}

func init() { proto.RegisterFile("notify.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 1668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x72, 0xdb, 0x38,
	0x12, 0x2e, 0xc9, 0x96, 0x2c, 0xb5, 0xe4, 0x3f, 0xc6, 0x71, 0xb4, 0x4e, 0xca, 0xa5, 0x45, 0x65,
	0x13, 0x57, 0x0e, 0xce, 0xee, 0xda, 0x5b, 0x49, 0x6d, 0xb2, 0x95, 0x95, 0xe5, 0x28, 0x51, 0x25,
	0xb2, 0xbd, 0xb0, 0xb3, 0xb9, 0x64, 0x0e, 0x08, 0x09, 0x5b, 0xac, 0x50, 0x84, 0x0a, 0x84, 0xac,
	0x52, 0xcd, 0x6d, 0xde, 0x65, 0x6e, 0xf3, 0x06, 0x73, 0x9b, 0x57, 0x98, 0x87, 0x99, 0xeb, 0x14,
	0x7e, 0x48, 0x82, 0xa4, 0x15, 0xdb, 0xa9, 0x99, 0x13, 0xd9, 0x5f, 0x7f, 0xe8, 0x06, 0xd0, 0xe8,
	0x46, 0x03, 0x9a, 0x21, 0x13, 0xfe, 0xf9, 0x6c, 0x77, 0xcc, 0x99, 0x60, 0x4e, 0x4d, 0x7d, 0x5c,
	0x16, 0x6c, 0x35, 0xc4, 0x6c, 0x4c, 0x23, 0x0d, 0x6f, 0x35, 0x47, 0xcc, 0xa3, 0x41, 0x22, 0x45,
	0x82, 0x4f, 0x5c, 0xa1, 0x25, 0xf4, 0x1c, 0x96, 0x7b, 0x94, 0x7a, 0x07, 0x01, 0x73, 0xbf, 0x44,
	0x47, 0xe2, 0xdc, 0x79, 0x0c, 0x55, 0x2d, 0xb4, 0x4a, 0xed, 0x85, 0x9d, 0xc6, 0x3f, 0x57, 0x77,
	0x63, 0xa3, 0xbb, 0x0a, 0xc7, 0x46, 0x8d, 0x4e, 0xe1, 0x4e, 0x32, 0x72, 0xc0, 0xc2, 0x48, 0x50,
	0x2e, 0xc7, 0xbf, 0x84, 0x65, 0x23, 0x65, 0xcc, 0x6c, 0xa6, 0x66, 0x6c, 0x35, 0xce, 0x92, 0xd1,
	0x00, 0x36, 0x13, 0xa3, 0x87, 0x6c, 0xe4, 0x87, 0x44, 0xf8, 0x2c, 0x94, 0x76, 0xf7, 0x00, 0x0e,
	0x58, 0x14, 0x65, 0x8c, 0xde, 0xb1, 0xe6, 0x16, 0xeb, 0xb0, 0x45, 0x43, 0x27, 0xb0, 0x91, 0xae,
	0x6e, 0x40, 0xb8, 0x3b, 0xa4, 0x6a, 0x91, 0xcf, 0xa1, 0xf9, 0xfa, 0x92, 0x86, 0xc2, 0x40, 0xc6,
	0xdc, 0x46, 0x6a, 0x2e, 0xd5, 0xe2, 0x0c, 0x13, 0xfd, 0x07, 0x1a, 0x1d, 0x57, 0xf8, 0x97, 0xbe,
	0x98, 0x49, 0x43, 0xbb, 0x50, 0x8b, 0x45, 0x63, 0xc4, 0x49, 0x8d, 0xc4, 0x1a, 0x9c, 0x70, 0xd0,
	0x77, 0xb0, 0x9c, 0x9a, 0x93, 0x06, 0xf6, 0x01, 0x52, 0xa0, 0x55, 0x6a, 0x97, 0xe7, 0xce, 0xc3,
	0xe2, 0x39, 0x9b, 0x50, 0x1d, 0x50, 0x31, 0x64, 0x5e, 0xab, 0xdc, 0x2e, 0xef, 0xd4, 0xb1, 0x91,
	0x10, 0x85, 0x55, 0xc5, 0xc2, 0xd4, 0xe5, 0x13, 0x5f, 0x48, 0x07, 0xff, 0x36, 0x4b, 0x35, 0x90,
	0x71, 0xb1, 0x99, 0x73, 0x61, 0xb4, 0x38, 0xc3, 0xbd, 0xd6, 0x4d, 0xe7, 0x33, 0x09, 0x3d, 0x1d,
	0x9e, 0xd8, 0x8d, 0x81, 0xe6, 0xb8, 0x31, 0x5a, 0x9c, 0xe1, 0xce, 0x75, 0x43, 0x60, 0x45, 0xf1,
	0xde, 0xf8, 0x97, 0xf4, 0xc3, 0x58, 0x7a, 0x79, 0x06, 0x0d, 0x0b, 0x31, 0x4e, 0xee, 0xe6, 0x9c,
	0x68, 0x25, 0xb6, 0x99, 0x73, 0x5d, 0xc4, 0xf1, 0x38, 0x98, 0xf8, 0x81, 0x67, 0xc7, 0x43, 0x01,
	0x73, 0xe2, 0xa1, 0x74, 0xd8, 0xe2, 0xcd, 0x35, 0xbf, 0x07, 0xf5, 0xb7, 0x94, 0x33, 0x7d, 0xe8,
	0x1e, 0x41, 0x55, 0x0b, 0xe6, 0xa4, 0xac, 0xa4, 0x66, 0x25, 0x8e, 0x8d, 0x16, 0x1d, 0xc3, 0xca,
	0x49, 0x40, 0x66, 0x94, 0x9f, 0x30, 0x3f, 0x54, 0x31, 0xfc, 0x1b, 0x54, 0xd4, 0xbf, 0x99, 0x8f,
	0x95, 0x92, 0x0a, 0xc6, 0x5a, 0x3b, 0x77, 0x16, 0xdb, 0x00, 0x3d, 0x41, 0x4f, 0x05, 0x55, 0x7b,
	0xb8, 0x06, 0x0b, 0xef, 0xe8, 0x4c, 0x99, 0xaa, 0x63, 0xf9, 0x8b, 0x7e, 0x2e, 0xc1, 0xba, 0xf6,
	0xa8, 0x56, 0xe3, 0x87, 0x17, 0x92, 0xf7, 0x2f, 0xa8, 0xc5, 0xa2, 0xf1, 0xfb, 0x17, 0x6b, 0x1f,
	0x02, 0x3a, 0x8a, 0x57, 0xef, 0x87, 0x17, 0x38, 0xa1, 0xce, 0x9b, 0x84, 0xd3, 0x86, 0x86, 0x19,
	0x74, 0x36, 0x1b, 0xd3, 0xd6, 0x42, 0xbb, 0xbc, 0x53, 0xc1, 0x36, 0x24, 0x1d, 0x62, 0x1a, 0xb1,
	0x09, 0x77, 0x69, 0x6b, 0x71, 0x8e, 0xc3, 0x98, 0x80, 0x13, 0x2a, 0xfa, 0xa1, 0x04, 0xcd, 0x58,
	0x50, 0xfb, 0xfc, 0x0f, 0xa8, 0x27, 0xb2, 0x99, 0xb9, 0x55, 0x28, 0x12, 0x15, 0x4e, 0x59, 0xce,
	0x2b, 0x58, 0xeb, 0x0e, 0x49, 0x78, 0x41, 0xbd, 0x74, 0x64, 0x79, 0xfe, 0xc8, 0x02, 0x19, 0x9d,
	0xc0, 0x7a, 0x22, 0xbc, 0xf7, 0x47, 0x3a, 0xf5, 0x5e, 0xc0, 0x4a, 0x16, 0xfc, 0xda, 0x6c, 0x72,
	0x54, 0xf4, 0x3d, 0x34, 0xba, 0x13, 0xce, 0x69, 0xe8, 0xc6, 0x85, 0x26, 0x16, 0x8d, 0x15, 0xab,
	0xd0, 0xc4, 0x1a, 0x9c, 0x70, 0x9c, 0x97, 0xb0, 0x6a, 0x26, 0x99, 0x0c, 0x2b, 0xcf, 0x1d, 0x96,
	0xa7, 0xa2, 0xa7, 0x70, 0xef, 0x88, 0x4e, 0x0f, 0x88, 0x10, 0x01, 0xc5, 0x74, 0xcc, 0xb8, 0xe8,
	0xb2, 0x89, 0x3e, 0x8b, 0x1b, 0x50, 0x51, 0xff, 0x6a, 0x16, 0x15, 0xac, 0x05, 0xf4, 0x77, 0x68,
	0x1d, 0xd1, 0xe9, 0xe9, 0x2c, 0x12, 0x74, 0x34, 0xa0, 0x51, 0x44, 0x2e, 0xe8, 0x35, 0x23, 0x7a,
	0xb0, 0x75, 0x44, 0xa7, 0x27, 0x94, 0x47, 0x2c, 0x24, 0xc1, 0x8d, 0xc6, 0x38, 0x0e, 0x2c, 0xf6,
	0x38, 0x1b, 0x99, 0x93, 0xa5, 0xfe, 0xd1, 0x27, 0xb8, 0x5b, 0xb4, 0x23, 0x4d, 0x74, 0x61, 0x35,
	0x87, 0x16, 0x8f, 0x71, 0x8e, 0x80, 0xf3, 0x23, 0xd0, 0x2b, 0x68, 0x7e, 0x64, 0x3c, 0xf0, 0xba,
	0x43, 0xa2, 0xe6, 0xf5, 0x14, 0x96, 0xb2, 0xc6, 0xac, 0xe2, 0x23, 0x39, 0xb1, 0xa1, 0x25, 0xcb,
	0xc0, 0xa9, 0x20, 0x82, 0x7e, 0xb3, 0x81, 0x5f, 0x17, 0x60, 0xf5, 0x8c, 0x33, 0x36, 0xee, 0x70,
	0xee, 0x5f, 0x52, 0xcf, 0x9c, 0x70, 0x95, 0xf1, 0xfd, 0xf0, 0x9c, 0x15, 0xcf, 0x54, 0xa2, 0xc2,
	0x29, 0xcb, 0x79, 0x00, 0xf5, 0xb7, 0x24, 0xd2, 0x11, 0x55, 0xfb, 0x57, 0xc3, 0x29, 0x20, 0xb7,
	0xbb, 0x1f, 0x7d, 0xf4, 0x43, 0x95, 0x96, 0x35, 0xac, 0x05, 0x67, 0x1b, 0xa0, 0x1f, 0x1d, 0xbb,
	0xee, 0x64, 0xec, 0x53, 0x4f, 0xa5, 0x64, 0x0d, 0x5b, 0x88, 0xb3, 0x25, 0x13, 0x56, 0x1e, 0x8e,
	0xbe, 0xd7, 0xaa, 0xa8, 0x90, 0x24, 0xb2, 0xf4, 0xa7, 0x66, 0x7d, 0x44, 0x46, 0xb4, 0x55, 0x55,
	0xca, 0x14, 0x70, 0x76, 0xa1, 0x8a, 0xe9, 0x94, 0x70, 0xaf, 0xb5, 0x94, 0xbf, 0x27, 0xba, 0x6c,
	0x34, 0x62, 0xa1, 0xd6, 0x62, 0xc3, 0xca, 0xa6, 0x74, 0xed, 0x46, 0x29, 0x6d, 0x27, 0x4c, 0xfd,
	0x06, 0x09, 0xd3, 0x86, 0x86, 0xde, 0x8c, 0x33, 0x7f, 0x44, 0xa3, 0x16, 0xe8, 0xfa, 0x64, 0x41,
	0x0e, 0x82, 0xe6, 0x21, 0x3d, 0xa7, 0xa1, 0x47, 0xb9, 0x5a, 0x55, 0x43, 0xad, 0x2a, 0x83, 0x39,
	0x8f, 0x60, 0x25, 0x96, 0x3b, 0x97, 0x44, 0x10, 0xde, 0x6a, 0x2a, 0x43, 0x39, 0x14, 0x7d, 0x80,
	0xf5, 0x9e, 0x4f, 0x03, 0xaf, 0xe7, 0xf3, 0x48, 0x1c, 0xb2, 0xa9, 0xba, 0x43, 0xff, 0x0b, 0x2b,
	0x59, 0xd0, 0xc4, 0xb6, 0x95, 0x4e, 0x3c, 0xab, 0xc7, 0x39, 0x3e, 0xda, 0x87, 0xc6, 0x11, 0x9d,
	0xea, 0x7d, 0xd6, 0xf7, 0x86, 0xfa, 0x2f, 0xde, 0x1b, 0x0a, 0xc6, 0x5a, 0x8b, 0xa6, 0x50, 0xbb,
	0xe5, 0x10, 0xe7, 0xaf, 0xb0, 0x70, 0xca, 0x5d, 0x53, 0x52, 0x56, 0xed, 0xe8, 0x31, 0xee, 0x61,
	0xa9, 0x93, 0x94, 0xc3, 0x48, 0xa8, 0x13, 0x75, 0x15, 0xe5, 0x30, 0x12, 0xa8, 0x0d, 0xb5, 0x1e,
	0xe3, 0x2e, 0x35, 0x19, 0xaf, 0xfe, 0xe3, 0x8c, 0x57, 0x02, 0xda, 0x81, 0x35, 0xb9, 0x20, 0x12,
	0x7d, 0x89, 0xae, 0xa9, 0x27, 0x9f, 0x60, 0xa3, 0x3b, 0x24, 0x63, 0x41, 0xb9, 0x64, 0xeb, 0x82,
	0x26, 0xd9, 0x9b, 0x50, 0x95, 0x40, 0xdf, 0x33, 0x74, 0x23, 0x49, 0x2b, 0xff, 0x27, 0xc1, 0x44,
	0x27, 0x43, 0x05, 0x6b, 0x41, 0xb2, 0xfb, 0xd1, 0x21, 0x0b, 0xa9, 0xc9, 0x04, 0x23, 0xa1, 0x0f,
	0xb0, 0xfc, 0x67, 0x98, 0x7d, 0x0a, 0xcb, 0x2a, 0x45, 0x93, 0x2b, 0x63, 0x1b, 0x20, 0x05, 0x8c,
	0x69, 0x0b, 0x41, 0x7d, 0x58, 0x39, 0xe3, 0x94, 0x44, 0x13, 0x4e, 0x07, 0x24, 0x6e, 0x89, 0x2c,
	0xa4, 0x58, 0x54, 0x2c, 0x25, 0xb6, 0x99, 0x68, 0x0f, 0x1a, 0x9d, 0x20, 0x18, 0x10, 0xae, 0xfb,
	0xfe, 0x87, 0x50, 0x51, 0xff, 0xc5, 0xe6, 0x44, 0xc2, 0x58, 0x2b, 0xd1, 0x00, 0x56, 0x3b, 0x41,
	0xe0, 0x93, 0xd0, 0xa5, 0x12, 0x90, 0x03, 0x11, 0x2c, 0xca, 0x5f, 0xe3, 0x39, 0x3f, 0x4e, 0xe9,
	0xe6, 0x76, 0x26, 0xcf, 0x61, 0xcd, 0x36, 0x77, 0x8b, 0x89, 0xfc, 0x56, 0x82, 0x06, 0xa6, 0x41,
	0xf2, 0x3c, 0xd8, 0x06, 0x88, 0x2d, 0x99, 0x98, 0xd4, 0xb1, 0x85, 0xc8, 0xe4, 0x8d, 0x25, 0x95,
	0xbc, 0x7a, 0x1e, 0x19, 0xcc, 0xe6, 0x60, 0x16, 0xc4, 0x3d, 0x4a, 0x06, 0x73, 0x9e, 0xc0, 0xda,
	0x80, 0xc8, 0x07, 0x8b, 0xe5, 0x6d, 0x51, 0xd9, 0x2a, 0xe0, 0xce, 0x2e, 0x38, 0x59, 0x4c, 0x79,
	0xd6, 0x95, 0xf2, 0x0a, 0x8d, 0xf3, 0x10, 0x96, 0xff, 0x37, 0xf1, 0x85, 0xaa, 0x36, 0x82, 0x8c,
	0xc6, 0xaa, 0x6e, 0x2e, 0xe0, 0x2c, 0x88, 0x08, 0x38, 0xc9, 0x9e, 0xa5, 0xb7, 0xdd, 0x5e, 0xfe,
	0x5e, 0xb1, 0x6e, 0xb9, 0x1c, 0x3d, 0xb9, 0x5b, 0xe6, 0x86, 0xe5, 0x97, 0x12, 0xdc, 0xcb, 0x55,
	0x1a, 0x55, 0x87, 0x4d, 0xf6, 0xbd, 0xa7, 0x97, 0x34, 0x88, 0xb3, 0x4f, 0x09, 0x56, 0x41, 0x2f,
	0xb7, 0x4b, 0xb7, 0x2d, 0xe8, 0x0b, 0xb7, 0x2e, 0xe8, 0x8b, 0xd7, 0x17, 0x74, 0xf4, 0xce, 0x3c,
	0x52, 0xfe, 0x90, 0x67, 0xdf, 0x3e, 0xd4, 0xbb, 0x43, 0x1a, 0x89, 0xf8, 0x89, 0xac, 0x85, 0xe2,
	0x13, 0x59, 0xe1, 0xd8, 0xa8, 0xd1, 0x0b, 0x58, 0x3e, 0x24, 0x7e, 0x30, 0x4b, 0xd2, 0xfb, 0x09,
	0x54, 0xec, 0x46, 0xd0, 0xf2, 0x9c, 0xf2, 0xb0, 0xa6, 0xa0, 0x9f, 0xca, 0xb0, 0x99, 0xac, 0xfe,
	0x84, 0x33, 0x6f, 0xe2, 0xc6, 0x87, 0xfd, 0x1b, 0x3a, 0xdc, 0x0e, 0xac, 0x27, 0xcd, 0xfa, 0x4d,
	0x5a, 0xdc, 0x22, 0xdb, 0x79, 0x06, 0xcd, 0xa3, 0xb1, 0x7b, 0xa3, 0xb0, 0x65, 0x88, 0x72, 0x60,
	0x27, 0x08, 0xd2, 0x81, 0x8b, 0x5f, 0x19, 0x68, 0x13, 0x65, 0xb2, 0x9d, 0x71, 0xff, 0xf3, 0x44,
	0xd0, 0x37, 0x2c, 0xf0, 0x0e, 0x58, 0x38, 0x89, 0x54, 0xfa, 0x54, 0x70, 0x01, 0x47, 0x3b, 0x50,
	0xed, 0x09, 0x6a, 0x4a, 0x41, 0x3f, 0xea, 0xf9, 0xa1, 0x1f, 0x0d, 0xa9, 0x2e, 0x05, 0xaa, 0x6d,
	0x89, 0x11, 0x19, 0xcb, 0x4e, 0x40, 0x79, 0x1a, 0x4b, 0x79, 0x21, 0x5d, 0x15, 0x4b, 0x75, 0x51,
	0x19, 0x35, 0xa2, 0x70, 0x37, 0x99, 0x58, 0x97, 0x05, 0x01, 0x75, 0x85, 0x6e, 0xc6, 0xde, 0x83,
	0x53, 0x54, 0x98, 0xa8, 0x3c, 0xb8, 0x62, 0x8d, 0x09, 0x07, 0x5f, 0x31, 0x0e, 0x11, 0xd8, 0x88,
	0x4f, 0x70, 0xc6, 0x4b, 0x1f, 0xd6, 0x0b, 0xb8, 0x71, 0x72, 0xbf, 0x98, 0x06, 0xa9, 0x8f, 0xe2,
	0x28, 0xf4, 0x18, 0xd6, 0x4f, 0xc8, 0x4c, 0xbe, 0xa6, 0x4e, 0x27, 0xae, 0x4b, 0x23, 0xb5, 0x0f,
	0x0e, 0x2c, 0xf6, 0xa3, 0xe3, 0x77, 0x66, 0xbb, 0xd4, 0x3f, 0xfa, 0xb1, 0x04, 0xf7, 0xd4, 0x75,
	0x2f, 0x1b, 0x45, 0x4a, 0xc3, 0x8e, 0x10, 0xc4, 0xfd, 0xa2, 0xe7, 0x93, 0xe9, 0xef, 0x4a, 0xf9,
	0xfe, 0x4e, 0x56, 0x52, 0x4d, 0xe6, 0x99, 0x6a, 0x6b, 0x61, 0xb2, 0x55, 0x8a, 0x65, 0xd3, 0x2a,
	0xe9, 0x7a, 0x9b, 0x43, 0x65, 0x63, 0x16, 0x37, 0x4f, 0xb2, 0x43, 0xd5, 0x6d, 0xa8, 0x0d, 0xa1,
	0x8f, 0xb0, 0x31, 0xf0, 0x43, 0x7f, 0x40, 0xc6, 0x9d, 0x20, 0x98, 0xe9, 0x78, 0x99, 0x3b, 0xda,
	0x94, 0xb7, 0x52, 0xe6, 0x29, 0x9a, 0xc6, 0xbc, 0xfc, 0xf5, 0x98, 0x0f, 0xa1, 0x95, 0x1a, 0x56,
	0x25, 0xf4, 0x7a, 0xe3, 0xfb, 0x50, 0x55, 0xf7, 0x75, 0x6c, 0xfc, 0x41, 0xb1, 0x0e, 0x1f, 0x4f,
	0x43, 0xea, 0xe9, 0x97, 0xbb, 0xe1, 0xa2, 0xd7, 0xe9, 0x45, 0x28, 0xdb, 0x75, 0xf3, 0x8e, 0xad,
	0xa8, 0x7f, 0x73, 0x32, 0xef, 0x17, 0x0d, 0x1d, 0x90, 0xc8, 0x77, 0x55, 0xa7, 0xaf, 0x99, 0xe8,
	0x11, 0xc0, 0xe9, 0x50, 0x35, 0xe0, 0xd2, 0x40, 0x0b, 0x96, 0x8c, 0x64, 0xe6, 0x18, 0x8b, 0xa8,
	0x23, 0x9f, 0xab, 0xee, 0x90, 0xf0, 0x0b, 0x7a, 0x5d, 0x65, 0xdf, 0x84, 0x6a, 0x67, 0xa4, 0xda,
	0x2d, 0x19, 0xc4, 0x32, 0x36, 0xd2, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0xcc, 0x2e, 0xbd,
	0x7a, 0x14, 0x00, 0x00,
}
