// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Coord struct {
	X                *int32 `protobuf:"varint,1,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Coord) Reset()                    { *m = Coord{} }
func (m *Coord) String() string            { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()               {}
func (*Coord) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *Coord) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Coord) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type PointInfo struct {
	Coord            *Coord           `protobuf:"bytes,1,req,name=Coord" json:"Coord,omitempty"`
	MapSN            *int32           `protobuf:"varint,2,req,name=MapSN" json:"MapSN,omitempty"`
	ZoneSN           *int32           `protobuf:"varint,3,req,name=ZoneSN" json:"ZoneSN,omitempty"`
	ElementType      *int32           `protobuf:"varint,4,req,name=ElementType" json:"ElementType,omitempty"`
	Building         *ElementBuilding `protobuf:"bytes,10,opt,name=Building" json:"Building,omitempty"`
	Camp             *ElementCamp     `protobuf:"bytes,11,opt,name=Camp" json:"Camp,omitempty"`
	NpcCity          *ElementNpcCity  `protobuf:"bytes,12,opt,name=NpcCity" json:"NpcCity,omitempty"`
	Pass             *ElementPass     `protobuf:"bytes,13,opt,name=Pass" json:"Pass,omitempty"`
	Resource         *ElementResource `protobuf:"bytes,14,opt,name=Resource" json:"Resource,omitempty"`
	Monster          *ElementMonster  `protobuf:"bytes,15,opt,name=Monster" json:"Monster,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PointInfo) Reset()                    { *m = PointInfo{} }
func (m *PointInfo) String() string            { return proto.CompactTextString(m) }
func (*PointInfo) ProtoMessage()               {}
func (*PointInfo) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *PointInfo) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *PointInfo) GetMapSN() int32 {
	if m != nil && m.MapSN != nil {
		return *m.MapSN
	}
	return 0
}

func (m *PointInfo) GetZoneSN() int32 {
	if m != nil && m.ZoneSN != nil {
		return *m.ZoneSN
	}
	return 0
}

func (m *PointInfo) GetElementType() int32 {
	if m != nil && m.ElementType != nil {
		return *m.ElementType
	}
	return 0
}

func (m *PointInfo) GetBuilding() *ElementBuilding {
	if m != nil {
		return m.Building
	}
	return nil
}

func (m *PointInfo) GetCamp() *ElementCamp {
	if m != nil {
		return m.Camp
	}
	return nil
}

func (m *PointInfo) GetNpcCity() *ElementNpcCity {
	if m != nil {
		return m.NpcCity
	}
	return nil
}

func (m *PointInfo) GetPass() *ElementPass {
	if m != nil {
		return m.Pass
	}
	return nil
}

func (m *PointInfo) GetResource() *ElementResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *PointInfo) GetMonster() *ElementMonster {
	if m != nil {
		return m.Monster
	}
	return nil
}

type ElementMonster struct {
	Level            *int32 `protobuf:"varint,1,req,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ElementMonster) Reset()                    { *m = ElementMonster{} }
func (m *ElementMonster) String() string            { return proto.CompactTextString(m) }
func (*ElementMonster) ProtoMessage()               {}
func (*ElementMonster) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *ElementMonster) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type ElementResource struct {
	Type             *int32 `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=Level" json:"Level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ElementResource) Reset()                    { *m = ElementResource{} }
func (m *ElementResource) String() string            { return proto.CompactTextString(m) }
func (*ElementResource) ProtoMessage()               {}
func (*ElementResource) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *ElementResource) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ElementResource) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type ElementNpcCity struct {
	SN               *int32 `protobuf:"varint,1,req,name=SN" json:"SN,omitempty"`
	IsCenter         *bool  `protobuf:"varint,2,req,name=IsCenter" json:"IsCenter,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ElementNpcCity) Reset()                    { *m = ElementNpcCity{} }
func (m *ElementNpcCity) String() string            { return proto.CompactTextString(m) }
func (*ElementNpcCity) ProtoMessage()               {}
func (*ElementNpcCity) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *ElementNpcCity) GetSN() int32 {
	if m != nil && m.SN != nil {
		return *m.SN
	}
	return 0
}

func (m *ElementNpcCity) GetIsCenter() bool {
	if m != nil && m.IsCenter != nil {
		return *m.IsCenter
	}
	return false
}

type ElementCamp struct {
	Visible          *bool  `protobuf:"varint,1,req,name=Visible" json:"Visible,omitempty"`
	RemainTimes      *int32 `protobuf:"varint,2,req,name=RemainTimes" json:"RemainTimes,omitempty"`
	Level            *int32 `protobuf:"varint,3,req,name=Level" json:"Level,omitempty"`
	Gold             *int32 `protobuf:"varint,4,req,name=Gold" json:"Gold,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ElementCamp) Reset()                    { *m = ElementCamp{} }
func (m *ElementCamp) String() string            { return proto.CompactTextString(m) }
func (*ElementCamp) ProtoMessage()               {}
func (*ElementCamp) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *ElementCamp) GetVisible() bool {
	if m != nil && m.Visible != nil {
		return *m.Visible
	}
	return false
}

func (m *ElementCamp) GetRemainTimes() int32 {
	if m != nil && m.RemainTimes != nil {
		return *m.RemainTimes
	}
	return 0
}

func (m *ElementCamp) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ElementCamp) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

type ElementPass struct {
	Type             *int32 `protobuf:"varint,1,req,name=Type" json:"Type,omitempty"`
	Level            *int32 `protobuf:"varint,2,req,name=Level" json:"Level,omitempty"`
	SN               *int32 `protobuf:"varint,3,req,name=SN" json:"SN,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ElementPass) Reset()                    { *m = ElementPass{} }
func (m *ElementPass) String() string            { return proto.CompactTextString(m) }
func (*ElementPass) ProtoMessage()               {}
func (*ElementPass) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *ElementPass) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ElementPass) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ElementPass) GetSN() int32 {
	if m != nil && m.SN != nil {
		return *m.SN
	}
	return 0
}

type ElementBuilding struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Type             *int32  `protobuf:"varint,2,req,name=Type" json:"Type,omitempty"`
	Level            *int32  `protobuf:"varint,3,req,name=Level" json:"Level,omitempty"`
	Coord            *Coord  `protobuf:"bytes,4,req,name=Coord" json:"Coord,omitempty"`
	IsUpgrade        *bool   `protobuf:"varint,5,req,name=IsUpgrade" json:"IsUpgrade,omitempty"`
	IsBroken         *bool   `protobuf:"varint,6,req,name=IsBroken" json:"IsBroken,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ElementBuilding) Reset()                    { *m = ElementBuilding{} }
func (m *ElementBuilding) String() string            { return proto.CompactTextString(m) }
func (*ElementBuilding) ProtoMessage()               {}
func (*ElementBuilding) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

func (m *ElementBuilding) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ElementBuilding) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *ElementBuilding) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *ElementBuilding) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *ElementBuilding) GetIsUpgrade() bool {
	if m != nil && m.IsUpgrade != nil {
		return *m.IsUpgrade
	}
	return false
}

func (m *ElementBuilding) GetIsBroken() bool {
	if m != nil && m.IsBroken != nil {
		return *m.IsBroken
	}
	return false
}

type AllianceOwnedPoint struct {
	Coord            *Coord  `protobuf:"bytes,1,req,name=Coord" json:"Coord,omitempty"`
	MapSN            *int32  `protobuf:"varint,2,req,name=MapSN" json:"MapSN,omitempty"`
	ZoneSN           *int32  `protobuf:"varint,3,req,name=ZoneSN" json:"ZoneSN,omitempty"`
	AllianceId       *string `protobuf:"bytes,4,req,name=AllianceId" json:"AllianceId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AllianceOwnedPoint) Reset()                    { *m = AllianceOwnedPoint{} }
func (m *AllianceOwnedPoint) String() string            { return proto.CompactTextString(m) }
func (*AllianceOwnedPoint) ProtoMessage()               {}
func (*AllianceOwnedPoint) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *AllianceOwnedPoint) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *AllianceOwnedPoint) GetMapSN() int32 {
	if m != nil && m.MapSN != nil {
		return *m.MapSN
	}
	return 0
}

func (m *AllianceOwnedPoint) GetZoneSN() int32 {
	if m != nil && m.ZoneSN != nil {
		return *m.ZoneSN
	}
	return 0
}

func (m *AllianceOwnedPoint) GetAllianceId() string {
	if m != nil && m.AllianceId != nil {
		return *m.AllianceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Coord)(nil), "protocol.Coord")
	proto.RegisterType((*PointInfo)(nil), "protocol.PointInfo")
	proto.RegisterType((*ElementMonster)(nil), "protocol.ElementMonster")
	proto.RegisterType((*ElementResource)(nil), "protocol.ElementResource")
	proto.RegisterType((*ElementNpcCity)(nil), "protocol.ElementNpcCity")
	proto.RegisterType((*ElementCamp)(nil), "protocol.ElementCamp")
	proto.RegisterType((*ElementPass)(nil), "protocol.ElementPass")
	proto.RegisterType((*ElementBuilding)(nil), "protocol.ElementBuilding")
	proto.RegisterType((*AllianceOwnedPoint)(nil), "protocol.AllianceOwnedPoint")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x1d, 0xa7, 0x75, 0xc6, 0x25, 0x91, 0x56, 0x80, 0x16, 0x84, 0x50, 0x64, 0x04, 0x2a,
	0x97, 0x1c, 0x22, 0x71, 0x82, 0x0b, 0x8d, 0x50, 0x15, 0x89, 0x9a, 0x6a, 0x53, 0x50, 0xcb, 0xcd,
	0xc4, 0x4b, 0x65, 0x61, 0xef, 0x5a, 0x5e, 0x17, 0x94, 0x47, 0xe0, 0x65, 0x10, 0x8f, 0x88, 0x76,
	0xf6, 0x27, 0x2e, 0x21, 0x88, 0x0b, 0x27, 0xfb, 0x9b, 0xf9, 0x66, 0xbe, 0xf9, 0xd9, 0x81, 0xa4,
	0xdb, 0x34, 0x5c, 0xcd, 0x9a, 0x56, 0x76, 0x92, 0xc4, 0xf8, 0x59, 0xcb, 0x2a, 0x7d, 0x02, 0xc3,
	0x85, 0x94, 0x6d, 0x41, 0x8e, 0x20, 0xb8, 0xa4, 0xc1, 0x34, 0x3c, 0x1e, 0xb2, 0xe0, 0x52, 0xa3,
	0x2b, 0x1a, 0x1a, 0x74, 0x95, 0xfe, 0x18, 0xc0, 0xe8, 0x5c, 0x96, 0xa2, 0x5b, 0x8a, 0xcf, 0x92,
	0x3c, 0xb5, 0x21, 0xc8, 0x4e, 0xe6, 0x93, 0x99, 0x4b, 0x36, 0x43, 0x33, 0xb3, 0x09, 0xef, 0xc2,
	0xf0, 0x2c, 0x6f, 0x56, 0x99, 0x4d, 0x63, 0x00, 0xb9, 0x0f, 0x07, 0x1f, 0xa5, 0xe0, 0xab, 0x8c,
	0x0e, 0xd0, 0x6c, 0x11, 0x99, 0x42, 0xf2, 0xa6, 0xe2, 0x35, 0x17, 0xdd, 0xc5, 0xa6, 0xe1, 0x34,
	0x42, 0x67, 0xdf, 0x44, 0x5e, 0x40, 0x7c, 0x72, 0x53, 0x56, 0x45, 0x29, 0xae, 0x29, 0x4c, 0x83,
	0xe3, 0x64, 0xfe, 0x60, 0xab, 0x6c, 0x89, 0x8e, 0xc0, 0x3c, 0x95, 0x3c, 0x87, 0x68, 0x91, 0xd7,
	0x0d, 0x4d, 0x30, 0xe4, 0xde, 0x4e, 0x88, 0x76, 0x32, 0xa4, 0x90, 0x39, 0x1c, 0x66, 0xcd, 0x7a,
	0x51, 0x76, 0x1b, 0x7a, 0x84, 0x6c, 0xba, 0xc3, 0xb6, 0x7e, 0xe6, 0x88, 0x3a, 0xfd, 0x79, 0xae,
	0x14, 0xbd, 0xb3, 0x27, 0xbd, 0x76, 0x32, 0xa4, 0xe8, 0x06, 0x18, 0x57, 0xf2, 0xa6, 0x5d, 0x73,
	0x3a, 0xde, 0xd3, 0x80, 0x23, 0x30, 0x4f, 0xd5, 0x55, 0x9d, 0x49, 0xa1, 0x3a, 0xde, 0xd2, 0xc9,
	0x9e, 0xaa, 0xac, 0x9f, 0x39, 0x62, 0xfa, 0x0c, 0xc6, 0xb7, 0x5d, 0x7a, 0x1b, 0x6f, 0xf9, 0x57,
	0x5e, 0xd9, 0x15, 0x1b, 0x90, 0xbe, 0x84, 0xc9, 0x6f, 0xc2, 0x84, 0x40, 0x84, 0x1b, 0x30, 0x3c,
	0xfc, 0xdf, 0x06, 0x87, 0xfd, 0xe0, 0x57, 0x5e, 0xc4, 0x0d, 0x63, 0x0c, 0xe1, 0x2a, 0xb3, 0x91,
	0xe1, 0x2a, 0x23, 0x0f, 0x21, 0x5e, 0xaa, 0x05, 0x17, 0xba, 0x76, 0x1d, 0x1a, 0x33, 0x8f, 0x53,
	0xe5, 0x17, 0x8e, 0xb3, 0xa7, 0x70, 0xf8, 0xa1, 0x54, 0xe5, 0xa7, 0xca, 0x28, 0xc7, 0xcc, 0x41,
	0xfd, 0x32, 0x18, 0xaf, 0xf3, 0x52, 0x5c, 0x94, 0x35, 0x57, 0xb6, 0x84, 0xbe, 0x69, 0x5b, 0xde,
	0xa0, 0x57, 0x9e, 0x6e, 0xe4, 0x54, 0x56, 0x85, 0x7d, 0x4a, 0xf8, 0x9f, 0x9e, 0x7a, 0x51, 0xdc,
	0xc8, 0x3f, 0xf7, 0x6a, 0x3b, 0x1b, 0xb8, 0xce, 0xd2, 0x9f, 0x81, 0x9f, 0x9c, 0x7f, 0x69, 0x04,
	0xa2, 0x2c, 0xaf, 0x4d, 0xb6, 0x11, 0xc3, 0x7f, 0xaf, 0x10, 0xfe, 0x49, 0xe1, 0x56, 0xb9, 0xfe,
	0xaa, 0xa2, 0xbf, 0x5e, 0xd5, 0x23, 0x18, 0x2d, 0xd5, 0xfb, 0xe6, 0xba, 0xcd, 0x0b, 0x4e, 0x87,
	0x38, 0xa9, 0xad, 0xc1, 0x0c, 0xfc, 0xa4, 0x95, 0x5f, 0xb8, 0xa0, 0x07, 0x6e, 0xe0, 0x06, 0xa7,
	0xdf, 0x03, 0x20, 0xaf, 0xab, 0xaa, 0xcc, 0xc5, 0x9a, 0xbf, 0xfb, 0x26, 0x78, 0x81, 0x17, 0xfd,
	0x7f, 0xae, 0xf9, 0x31, 0x80, 0x93, 0x5a, 0x9a, 0x8e, 0x46, 0xac, 0x67, 0xf9, 0x15, 0x00, 0x00,
	0xff, 0xff, 0xcb, 0xce, 0x75, 0xbc, 0x8d, 0x04, 0x00, 0x00,
}
